In [ ]:
import numpy as np
import pandas as pd

import cv2
from PIL import Image
from torchvision import transforms

import tempfile
import os
import joblib
from ultralytics import YOLO

from segmentation.modelsUnet import UNet4Levels, preprocess_image, predict_masks
from segmentation.features import extract_features
from classification.models import CytologyClassifier, predict_label

from app.backend.helpers import *  

import matplotlib.pyplot as plt
import matplotlib.patches as patches

from dotenv import load_dotenv
from pathlib import Path


load_dotenv()

CLASS_NAMES = os.getenv("CLASS_NAMES", "HSIL,LSIL,NSIL").split(",")
ARCHITECTURE = os.getenv("ARCHITECTURE", "resnet18")
CNN_MODEL_PATH = os.getenv("CNN_MODEL_PATH", r"C:\Users\aleks\OneDrive\Documents\inzynierka\classification\classification_models\resnet18\16_0_0001_50_1110.pth")
UNET_MODEL_PATH = os.getenv("UNET_MODEL_PATH", r"C:\Users\aleks\OneDrive\Documents\inzynierka\segmentation\unet4_cell_nucleus_4_50_1310.pth")
THRESHOLD_NUCLEI = float(os.getenv("THRESHOLD_NUCLEI", 0.7))
THRESHOLD_CELLS = float(os.getenv("THRESHOLD_CELLS", 0.3))
YOLO_MODEL_PATH = os.getenv("YOLO_MODEL_PATH", r"C:\Users\aleks\OneDrive\Documents\inzynierka\yolo_models\models\yolo_detector_2107_100_20_16_7682\weights\best.pt")
ML_MODEL_PATH = os.getenv("ML_MODEL_PATH", r'C:\Users\aleks\OneDrive\Documents\inzynierka\segmentation\models_paths\best_model_RandomForest_new_unet.pkl')
FUSED_MODEL_PATH = os.getenv("FUSED_MODEL_PATH", r"C:\Users\aleks\OneDrive\Documents\inzynierka\segmentation\models_paths\joined\model_probs_1410_SVM2.pkl")
API_KEY = os.getenv("API_KEY", os.getenv("api_key", ''))
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


unet = UNet4Levels(in_channels=3, out_channels=2)
unet.load_state_dict(torch.load(UNET_MODEL_PATH, map_location=device))
unet.to(device).eval()

yolo = YOLO(YOLO_MODEL_PATH)

ml_model = joblib.load(ML_MODEL_PATH)
label_encoder = ml_model['label_encoder']

fused_model = joblib.load(FUSED_MODEL_PATH)
label_encode_fused = fused_model['label_encoder']

cnn_classifier = CytologyClassifier(num_classes=len(CLASS_NAMES), architecture=ARCHITECTURE)
cnn_classifier.load(CNN_MODEL_PATH)
cnn_classifier.model.eval().to(device)


def get_info(image_path, show_image=True):
    image = Image.open(image_path).convert("RGB")
    image_np = np.array(image)

    results = yolo(image_path, conf=0.25, iou=0.5, agnostic_nms=False)
    boxes_tensor = results[0].boxes.xyxy.cpu()
    classes_tensor = results[0].boxes.cls.cpu().int()

    boxes_array = boxes_tensor.numpy()
    keep_ids = nms_keep_largest_box(boxes_array, iou_thresh=0.4)

    boxes_tensor = boxes_tensor[keep_ids]
    classes_tensor = classes_tensor[keep_ids]

    cell_mask = (classes_tensor == 0) | (classes_tensor == 1) | (classes_tensor == 2)
    boxes = boxes_tensor[cell_mask].numpy().astype(int)

    predicted_classes_cnn = {}
    predicted_classed_ml = {}
    predicted_classed_fused = {}
    features_list = {}
    probs = {}
    crop_paths = {}
    probs_list = []

    bbox_image_path = None
    if show_image:
        fig, ax = plt.subplots(figsize=(7.68, 5.12), dpi=100)
        ax.imshow(image_np)
        for idx, (x1, y1, x2, y2) in enumerate(boxes):
            rect = patches.Rectangle(
                (x1, y1), x2 - x1, y2 - y1,
                linewidth=2,
                edgecolor= '#f7c873',
                facecolor='none'
            )
            ax.add_patch(rect)
            ax.text(
                x1, max(0, y1 - 5), str(idx),
                color='#3a5ba0',  
                fontsize=12, weight='bold',
                bbox=dict(facecolor='white', alpha=0.5, edgecolor='none')
            )
        ax.set_axis_off()
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp_bbox:
            fig.savefig(tmp_bbox.name, bbox_inches='tight', pad_inches=0, dpi=100)
            bbox_image_path = tmp_bbox.name
        plt.close(fig)
        im = Image.open(bbox_image_path)
        im = im.resize((768, 512), Image.LANCZOS)
        im.save(bbox_image_path)

    for idx, (x1, y1, x2, y2) in enumerate(boxes):
        crop = image_np[y1:y2, x1:x2]
        if crop.size == 0:
            continue

        yolo_class = None
        for i, box in enumerate(boxes_tensor.numpy().astype(int)):
            if np.array_equal(box, [x1, y1, x2, y2]):
                yolo_class = int(classes_tensor[i].item())
                break

        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp_crop:
            cv2.imwrite(tmp_crop.name, cv2.cvtColor(crop, cv2.COLOR_RGB2BGR))
            tmp_path = tmp_crop.name
            crop_paths[idx] = tmp_path

        if yolo_class == 1:
            predicted_classes_cnn[idx] = 'HSIL/LSIL_group'
            predicted_classed_fused[idx] = 'HSIL/LSIL_group'
            probs_list.append([0.7, 0.3, 0.0])
            continue

        _, tensor = preprocess_image(tmp_path)
        masks = predict_masks(unet, tensor, device, threshold_nuclei=THRESHOLD_NUCLEI, threshold_cell=THRESHOLD_CELLS)
        mask_nucleus = cv2.resize(masks[1], (crop.shape[1], crop.shape[0]))
        best_nucleus = select_best_nucleus(mask_nucleus, crop.shape[:2])
        mask_cell = cv2.resize(masks[0], (crop.shape[1], crop.shape[0])) * 255

        features = extract_features(best_nucleus, mask_cell)
        
        if features is None or len(features) == 0:
            print(f"Pominięto komórkę {idx} - brak features")
            continue
            
        if all(value == 0 for value in features.values()):
            print(f"Pominięto komórkę {idx} - wszystkie features równe 0")
            continue
            
        features_list[idx] = features

        predict_class_ml = predict_ml(ml_model['model'], label_encoder, features)
        predicted_classed_ml[idx] = predict_class_ml

        predict_class_cnn = predict_label(cnn_classifier, crop)
        predicted_classes_cnn[idx] = predict_class_cnn[0]

        rf_predictions = predict_fused_func(fused_model['model'], label_encode_fused, cnn_classifier,   ml_model['model'], unet, device, tmp_path)
        predicted_classed_fused[idx] = rf_predictions

        probs_fused = predict_fused_func(
            fused_model['model'], label_encode_fused, cnn_classifier, ml_model['model'], unet, device, tmp_path, probs_output=True
        )
        probs[idx] = {
            'fused': probs_fused
        }
        probs_list.append(probs_fused)
    
    all_indices = set(predicted_classes_cnn.keys()) | set(predicted_classed_ml.keys()) | set(predicted_classed_fused.keys())
    rows = []
    for idx in sorted(all_indices):
        rows.append({
            "idx": idx,
            "predict_vgg": predicted_classes_cnn.get(idx, None),
            "predict_gbm": predicted_classed_ml.get(idx, None),
            "predicted_classed_fused": predicted_classed_fused.get(idx, None),
        })

    df_preds = pd.DataFrame(rows)

    return features_list, predicted_classed_fused, probs_list, df_preds, bbox_image_path, crop_paths

c:\Users\aleks\OneDrive\Documents\inzynierka\inz\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\aleks\OneDrive\Documents\inzynierka\inz\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [52]:
import pandas as pd 

def get_metric(folder_path, class_name):
    class_names = CLASS_NAMES
    success_count_mean = 0
    success_count_max = 0
    success_count_weight = 0
    total_count = 0
    filenames = os.listdir(folder_path)
    true_classes = [class_name] * len(os.listdir(folder_path))
    predicted_classes_mean = []
    predicted_classes_max = []
    predicted_classes_weight = []
    mean_vectors = []
    max_wectors = []
    weight_wectors = []
    probs = []

    for filename in os.listdir(folder_path):
        if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff')):
            image_path = os.path.join(folder_path, filename)
            features_list, predicted_classed_fused, probs_list, df_preds, bbox_image_path, crop_pat = get_info(image_path, show_image=False)
            probs.append(probs_list)
            if len(probs_list) == 0:
                print(f"⚠️ Warning: No cells detected in {filename} - skipping")
                mean_vectors.append(None)
                predicted_classes_mean.append(None)
                max_wectors.append(None)
                predicted_classes_max.append(None)
                weight_wectors.append(None)
                predicted_classes_weight.append(None)                
                continue

            mean_vector = np.mean(probs_list, axis=0)
            predicted_class_mean_vector = class_names[np.argmax(mean_vector)]
            mean_vectors.append(mean_vector)
            predicted_classes_mean.append(predicted_class_mean_vector)

            slide_max = np.max(probs_list, axis=0)
            predicted_class_slide_max = class_names[np.argmax(slide_max)]
            max_wectors.append(slide_max)
            predicted_classes_max.append(predicted_class_slide_max)

            weights = np.max(probs_list, axis=1)
            weighted_wector = np.average(probs_list, axis=0, weights=weights)
            predicted_class_slide_weighted = class_names[np.argmax(weighted_wector)]
            weight_wectors.append(weighted_wector)
            predicted_classes_weight.append(predicted_class_slide_weighted)


            if predicted_class_mean_vector == class_name:
                success_count_mean += 1
            if predicted_class_slide_max == class_name:
                success_count_max += 1
            if predicted_class_slide_weighted == class_name:
                success_count_weight += 1
            total_count += 1
            

    accuracy_mean = success_count_mean / total_count if total_count > 0 else 0
    accuracy_max = success_count_max / total_count if total_count > 0 else 0
    accuracy_weight = success_count_weight / total_count if total_count > 0 else 0

    df_accuracy = pd.DataFrame({
        'Method': ['Mean Vector', 'Slide Max', 'Weighted Average'],
        'Accuracy': [accuracy_mean, accuracy_max, accuracy_weight]
    })
    df = pd.DataFrame({'Filename': filenames, 
                       'True Class': true_classes, 
                       'Predicted Class_Mean': predicted_classes_mean, 
                       'Mean Vector': mean_vectors, 
                       'Predicted Class_Max': predicted_classes_max, 
                       'Max Vector': max_wectors, 
                       'Predicted Class_Weighted': predicted_classes_weight, 
                       'Weight Vector': weight_wectors, 
                       'Probs': probs})

    return df_accuracy, df

In [53]:
accuracy_h, df_h = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40", "HSIL")

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\10b.bmp: 480x768 14 cells, 2 HSIL_groups, 70.5ms
Speed: 4.1ms preprocess, 70.5ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 14 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\11b.bmp: 480x768 7 cells, 1 HSIL_group, 82.3ms
Speed: 3.3ms preprocess, 82.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\12b.bmp: 480x768 19 cells, 75.1ms
Speed: 3.4ms preprocess, 75.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\13b.bmp: 480x768 7 cells, 2 HSIL_groups, 69.8ms
Speed: 3.4ms preprocess, 69.8ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\14b.bmp: 480x768 6 cells, 1 HSIL_group, 67.7ms
Speed: 3.7ms preprocess, 67.7ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\15b.bmp: 480x768 15 cells, 2 HSIL_groups, 86.0ms
Speed: 4.6ms preprocess, 86.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\16b.bmp: 480x768 23 cells, 1 HSIL_group, 79.6ms
Speed: 3.0ms preprocess, 79.6ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\17b.bmp: 480x768 6 cells, 2 HSIL_groups, 65.1ms
Speed: 3.5ms preprocess, 65.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\19b.bmp: 480x768 7 cells, 61.3ms
Speed: 3.3ms preprocess, 61.3ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\1b.bmp: 480x768 10 cells, 1 HSIL_group, 71.7ms
Speed: 3.4ms preprocess, 71.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\20b.bmp: 480x768 6 cells, 67.5ms
Speed: 3.1ms preprocess, 67.5ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\22b+.bmp: 480x768 10 cells, 71.8ms
Speed: 3.5ms preprocess, 71.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\23b.bmp: 480x768 7 cells, 68.7ms
Speed: 3.4ms preprocess, 68.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\24b.bmp: 480x768 5 cells, 68.1ms
Speed: 3.1ms preprocess, 68.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\25b.bmp: 480x768 7 cells, 74.5ms
Speed: 3.2ms preprocess, 74.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\25c.bmp: 480x768 2 cells, 83.0ms
Speed: 3.5ms preprocess, 83.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\26b.bmp: 480x768 3 cells, 61.5ms
Speed: 3.3ms preprocess, 61.5ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\27b.bmp: 480x768 2 cells, 71.9ms
Speed: 3.5ms preprocess, 71.9ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\28b.bmp: 480x768 3 cells, 64.7ms
Speed: 4.2ms preprocess, 64.7ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\29b.bmp: 480x768 8 cells, 1 HSIL_group, 70.1ms
Speed: 5.4ms preprocess, 70.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\2b.bmp: 480x768 5 cells, 61.3ms
Speed: 2.8ms preprocess, 61.3ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\30b.bmp: 480x768 2 cells, 83.0ms
Speed: 5.2ms preprocess, 83.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\31b.bmp: 480x768 3 cells, 73.5ms
Speed: 4.7ms preprocess, 73.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\32b.bmp: 480x768 1 cell, 65.6ms
Speed: 3.3ms preprocess, 65.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\33b.bmp: 480x768 5 cells, 1 HSIL_group, 66.6ms
Speed: 3.2ms preprocess, 66.6ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\34b.bmp: 480x768 10 cells, 59.3ms
Speed: 3.4ms preprocess, 59.3ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\35b.bmp: 480x768 5 cells, 62.3ms
Speed: 3.1ms preprocess, 62.3ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\35c.bmp: 480x768 6 cells, 68.1ms
Speed: 3.0ms preprocess, 68.1ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\36b.bmp: 480x768 2 cells, 69.2ms
Speed: 3.2ms preprocess, 69.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\37b.bmp: 480x768 6 cells, 63.9ms
Speed: 4.0ms preprocess, 63.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\39b.bmp: 480x768 5 cells, 62.8ms
Speed: 4.6ms preprocess, 62.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\3b.bmp: 480x768 2 cells, 59.0ms
Speed: 3.3ms preprocess, 59.0ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\40b.bmp: 480x768 7 cells, 65.4ms
Speed: 3.5ms preprocess, 65.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\41b.bmp: 480x768 5 cells, 60.1ms
Speed: 3.1ms preprocess, 60.1ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\42b.bmp: 480x768 10 cells, 69.4ms
Speed: 3.3ms preprocess, 69.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\43b.bmp: 480x768 12 cells, 63.1ms
Speed: 3.2ms preprocess, 63.1ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\44b.bmp: 480x768 4 cells, 64.4ms
Speed: 3.5ms preprocess, 64.4ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\45b.bmp: 480x768 8 cells, 68.6ms
Speed: 3.4ms preprocess, 68.6ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\46b.bmp: 480x768 8 cells, 64.2ms
Speed: 3.3ms preprocess, 64.2ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\47b.bmp: 480x768 4 cells, 67.8ms
Speed: 3.7ms preprocess, 67.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\48b.bmp: 480x768 4 cells, 1 HSIL_group, 77.0ms
Speed: 3.3ms preprocess, 77.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\49b.bmp: 480x768 10 cells, 2 HSIL_groups, 75.9ms
Speed: 3.1ms preprocess, 75.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\4b.bmp: 480x768 7 cells, 1 HSIL_group, 62.7ms
Speed: 3.1ms preprocess, 62.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\4c.bmp: 480x768 5 cells, 67.5ms
Speed: 3.0ms preprocess, 67.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\50b.bmp: 480x768 7 cells, 1 HSIL_group, 64.5ms
Speed: 4.2ms preprocess, 64.5ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\51b.bmp: 480x768 1 cell, 77.1ms
Speed: 3.3ms preprocess, 77.1ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\52b.bmp: 480x768 7 cells, 68.7ms
Speed: 3.4ms preprocess, 68.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\52c.bmp: 480x768 10 cells, 66.4ms
Speed: 3.2ms preprocess, 66.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\53b.bmp: 480x768 2 cells, 84.7ms
Speed: 3.4ms preprocess, 84.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\53c.bmp: 480x768 8 cells, 56.8ms
Speed: 3.4ms preprocess, 56.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\53d.bmp: 480x768 3 cells, 68.8ms
Speed: 4.1ms preprocess, 68.8ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\54b.bmp: 480x768 18 cells, 73.7ms
Speed: 3.6ms preprocess, 73.7ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\57b.bmp: 480x768 14 cells, 71.6ms
Speed: 3.3ms preprocess, 71.6ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\58b.bmp: 480x768 16 cells, 69.7ms
Speed: 4.2ms preprocess, 69.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\59b.bmp: 480x768 16 cells, 63.1ms
Speed: 3.5ms preprocess, 63.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\5b.bmp: 480x768 4 cells, 86.4ms
Speed: 3.0ms preprocess, 86.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\60b.bmp: 480x768 8 cells, 75.1ms
Speed: 4.0ms preprocess, 75.1ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\6b.bmp: 480x768 6 cells, 1 HSIL_group, 64.5ms
Speed: 3.7ms preprocess, 64.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\7b.bmp: 480x768 4 cells, 65.6ms
Speed: 3.6ms preprocess, 65.6ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\8b.bmp: 480x768 11 cells, 1 HSIL_group, 71.4ms
Speed: 4.0ms preprocess, 71.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\8c.bmp: 480x768 5 cells, 1 HSIL_group, 69.5ms
Speed: 3.3ms preprocess, 69.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 40\9b.bmp: 480x768 19 cells, 1 HSIL_group, 69.1ms
Speed: 3.5ms preprocess, 69.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 16 - wszystkie features równe 0

In [54]:
accuracy_h

             Method  Accuracy
0       Mean Vector  0.677419
1         Slide Max  0.645161
2  Weighted Average  0.677419

In [59]:
df_h.to_excel('HSIL_pow40.xlsx', index=False)

In [60]:
accuracy_l, df_l = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40", "LSIL")

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\10b.bmp: 480x768 2 cells, 113.8ms
Speed: 6.2ms preprocess, 113.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\11b.bmp: 480x768 12 cells, 57.1ms
Speed: 3.6ms preprocess, 57.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\12b.bmp: 480x768 6 cells, 70.3ms
Speed: 3.5ms preprocess, 70.3ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\13b.bmp: 480x768 2 cells, 79.9ms
Speed: 3.1ms preprocess, 79.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\14b.bmp: 480x768 8 cells, 64.3ms
Speed: 3.4ms preprocess, 64.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\14c.bmp: 480x768 5 cells, 86.6ms
Speed: 3.6ms preprocess, 86.6ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\15b.bmp: 480x768 13 cells, 71.9ms
Speed: 3.9ms preprocess, 71.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\16b.bmp: 480x768 9 cells, 68.4ms
Speed: 3.1ms preprocess, 68.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\17b.bmp: 480x768 3 cells, 84.9ms
Speed: 3.2ms preprocess, 84.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\17c.bmp: 480x768 12 cells, 68.2ms
Speed: 3.5ms preprocess, 68.2ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\18b.bmp: 480x768 12 cells, 76.6ms
Speed: 4.9ms preprocess, 76.6ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\19b.bmp: 480x768 6 cells, 67.4ms
Speed: 3.3ms preprocess, 67.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\1b.bmp: 480x768 4 cells, 67.1ms
Speed: 3.5ms preprocess, 67.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\20b.bmp: 480x768 1 cell, 71.0ms
Speed: 3.7ms preprocess, 71.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\21b.bmp: 480x768 9 cells, 77.1ms
Speed: 3.1ms preprocess, 77.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\22b.bmp: 480x768 7 cells, 67.5ms
Speed: 3.8ms preprocess, 67.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\23b.bmp: 480x768 9 cells, 77.0ms
Speed: 5.1ms preprocess, 77.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\24b.bmp: 480x768 4 cells, 69.8ms
Speed: 3.6ms preprocess, 69.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\25b.bmp: 480x768 6 cells, 84.6ms
Speed: 5.4ms preprocess, 84.6ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\26b.bmp: 480x768 (no detections), 63.7ms
Speed: 3.6ms preprocess, 63.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
⚠️ Warning: No cells detected in 26b.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\27b.bmp: 480x768 11 cells, 74.1ms
Speed: 4.0ms preprocess, 74.1ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\28b.bmp: 480x768 6 cells, 67.2ms
Speed: 3.4ms preprocess, 67.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\29b.bmp: 480x768 7 cells, 84.8ms
Speed: 4.8ms preprocess, 84.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\2b.bmp: 480x768 3 cells, 75.0ms
Speed: 4.8ms preprocess, 75.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\30b.bmp: 480x768 8 cells, 69.4ms
Speed: 3.2ms preprocess, 69.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\31b.bmp: 480x768 6 cells, 72.2ms
Speed: 3.9ms preprocess, 72.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\32b.bmp: 480x768 6 cells, 73.3ms
Speed: 3.8ms preprocess, 73.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\33b.bmp: 480x768 5 cells, 78.2ms
Speed: 4.5ms preprocess, 78.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\34b.bmp: 480x768 14 cells, 2 HSIL_groups, 70.5ms
Speed: 4.4ms preprocess, 70.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\3b.bmp: 480x768 12 cells, 1 HSIL_group, 89.8ms
Speed: 6.0ms preprocess, 89.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\5b.bmp: 480x768 3 cells, 87.4ms
Speed: 3.4ms preprocess, 87.4ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\6b.bmp: 480x768 12 cells, 80.5ms
Speed: 4.8ms preprocess, 80.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\7b.bmp: 480x768 4 cells, 70.6ms
Speed: 3.1ms preprocess, 70.6ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\8b.bmp: 480x768 4 cells, 80.9ms
Speed: 3.4ms preprocess, 80.9ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow 40\9b.bmp: 480x768 3 cells, 80.9ms
Speed: 6.0ms preprocess, 80.9ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)

In [61]:
accuracy_l

             Method  Accuracy
0       Mean Vector  0.823529
1         Slide Max  0.705882
2  Weighted Average  0.823529

In [62]:
df_l.to_excel('LSIL_pow40.xlsx', index=False)

In [63]:
accuracy_n, df_n = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40", "NSIL")

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\10b.bmp: 480x768 3 cells, 70.1ms
Speed: 3.9ms preprocess, 70.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\11b.bmp: 480x768 1 cell, 68.5ms
Speed: 3.4ms preprocess, 68.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\12b.bmp: 480x768 1 cell, 65.6ms
Speed: 3.9ms preprocess, 65.6ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\13b.bmp: 480x768 1 cell, 91.5ms
Speed: 3.6ms preprocess, 91.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\14b.bmp: 480x768 2 cells, 85.9ms
Speed: 3.4ms preprocess, 85.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\15b.bmp: 480x768 1 cell, 71.0ms
Speed: 2.8ms preprocess, 71.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\16b.bmp: 480x768 2 cells, 80.5ms
Speed: 3.2ms preprocess, 80.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\17b.bmp: 768x480 2 cells, 87.1ms
Speed: 3.2ms preprocess, 87.1ms inference, 2.0ms postprocess per image at shape (1, 3, 768, 480)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\18b.bmp: 512x768 3 cells, 85.5ms
Speed: 3.5ms preprocess, 85.5ms inference, 1.2ms postprocess per image at shape (1, 3, 512, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\18c.bmp: 480x768 2 cells, 68.6ms
Speed: 3.4ms preprocess, 68.6ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\19b.bmp: 480x768 1 cell, 80.8ms
Speed: 3.0ms preprocess, 80.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\19c.bmp: 480x768 1 cell, 99.0ms
Speed: 3.2ms preprocess, 99.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\19d.bmp: 480x768 1 cell, 71.7ms
Speed: 4.1ms preprocess, 71.7ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\1b.bmp: 480x768 1 cell, 70.8ms
Speed: 3.2ms preprocess, 70.8ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\20b.bmp: 480x768 1 cell, 68.5ms
Speed: 4.3ms preprocess, 68.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\20c.bmp: 480x768 4 cells, 88.8ms
Speed: 3.2ms preprocess, 88.8ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\21b.bmp: 480x768 3 cells, 72.7ms
Speed: 4.0ms preprocess, 72.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\22b.bmp: 480x768 1 cell, 68.8ms
Speed: 4.6ms preprocess, 68.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\22c.bmp: 480x768 1 cell, 66.4ms
Speed: 3.7ms preprocess, 66.4ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\22d.bmp: 480x768 1 cell, 83.8ms
Speed: 4.3ms preprocess, 83.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\23b.bmp: 480x768 1 cell, 63.2ms
Speed: 3.9ms preprocess, 63.2ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\24b.bmp: 480x768 1 cell, 75.2ms
Speed: 5.3ms preprocess, 75.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\25b.bmp: 480x768 1 cell, 70.9ms
Speed: 4.1ms preprocess, 70.9ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\26b.bmp: 480x768 1 cell, 69.3ms
Speed: 6.6ms preprocess, 69.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\27b.bmp: 480x768 1 cell, 86.1ms
Speed: 4.9ms preprocess, 86.1ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\27c.bmp: 480x768 1 cell, 82.2ms
Speed: 4.6ms preprocess, 82.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\27d.bmp: 480x768 1 cell, 65.8ms
Speed: 3.3ms preprocess, 65.8ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\28b.bmp: 480x768 1 cell, 69.9ms
Speed: 3.3ms preprocess, 69.9ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\29b.bmp: 480x768 1 cell, 86.5ms
Speed: 3.3ms preprocess, 86.5ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\2b.bmp: 480x768 1 cell, 81.1ms
Speed: 3.9ms preprocess, 81.1ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\30b.bmp: 480x768 1 cell, 69.7ms
Speed: 3.3ms preprocess, 69.7ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\30c.bmp: 480x768 1 cell, 81.0ms
Speed: 5.0ms preprocess, 81.0ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\30d.bmp: 480x768 1 cell, 69.5ms
Speed: 3.1ms preprocess, 69.5ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\31b.bmp: 480x768 1 cell, 77.8ms
Speed: 4.8ms preprocess, 77.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\31c.bmp: 480x768 1 cell, 85.7ms
Speed: 5.6ms preprocess, 85.7ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\32b.bmp: 480x768 1 cell, 79.3ms
Speed: 3.3ms preprocess, 79.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\33b.bmp: 480x768 1 cell, 84.6ms
Speed: 4.8ms preprocess, 84.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\34b.bmp: 480x768 3 cells, 74.7ms
Speed: 4.8ms preprocess, 74.7ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\34c.bmp: 480x768 5 cells, 84.2ms
Speed: 3.6ms preprocess, 84.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\35b.bmp: 480x768 1 cell, 84.1ms
Speed: 4.1ms preprocess, 84.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\36b.bmp: 480x768 1 cell, 75.8ms
Speed: 3.7ms preprocess, 75.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\37b.bmp: 480x768 2 cells, 72.8ms
Speed: 4.3ms preprocess, 72.8ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\38b.bmp: 480x768 1 cell, 74.2ms
Speed: 5.4ms preprocess, 74.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\39b.bmp: 480x768 2 cells, 74.3ms
Speed: 3.0ms preprocess, 74.3ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\3b.bmp: 480x768 4 cells, 83.0ms
Speed: 4.0ms preprocess, 83.0ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\40b.bmp: 480x768 1 cell, 70.0ms
Speed: 3.3ms preprocess, 70.0ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\42b.bmp: 480x768 1 cell, 70.9ms
Speed: 3.5ms preprocess, 70.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 42b.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43b.bmp: 480x768 7 cells, 65.4ms
Speed: 3.8ms preprocess, 65.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43c.bmp: 480x768 5 cells, 70.9ms
Speed: 4.2ms preprocess, 70.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43d.bmp: 480x768 3 cells, 72.9ms
Speed: 3.5ms preprocess, 72.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43e.bmp: 480x768 1 cell, 66.9ms
Speed: 3.8ms preprocess, 66.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43f.bmp: 480x768 2 cells, 63.4ms
Speed: 4.0ms preprocess, 63.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\43g.bmp: 480x768 5 cells, 66.3ms
Speed: 3.6ms preprocess, 66.3ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\44b.bmp: 480x768 4 cells, 66.3ms
Speed: 3.3ms preprocess, 66.3ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\44c.bmp: 480x768 10 cells, 73.9ms
Speed: 4.1ms preprocess, 73.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\44d.bmp: 480x768 4 cells, 76.2ms
Speed: 3.3ms preprocess, 76.2ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\45b.bmp: 480x768 1 cell, 69.4ms
Speed: 3.8ms preprocess, 69.4ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\45c.bmp: 480x768 1 cell, 75.8ms
Speed: 5.2ms preprocess, 75.8ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 45c.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\46b.bmp: 480x768 1 cell, 78.7ms
Speed: 3.7ms preprocess, 78.7ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 46b.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\47b.bmp: 480x768 1 cell, 81.2ms
Speed: 4.6ms preprocess, 81.2ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 47b.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\47c.bmp: 480x768 1 cell, 75.8ms
Speed: 3.4ms preprocess, 75.8ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\47d.bmp: 480x768 1 cell, 73.6ms
Speed: 5.7ms preprocess, 73.6ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 47d.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\47e.bmp: 480x768 1 cell, 67.6ms
Speed: 3.7ms preprocess, 67.6ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 47e.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\48b.bmp: 480x768 1 cell, 90.4ms
Speed: 3.8ms preprocess, 90.4ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\48c.bmp: 480x768 1 cell, 70.6ms
Speed: 4.8ms preprocess, 70.6ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\48d.bmp: 480x768 1 cell, 64.7ms
Speed: 3.0ms preprocess, 64.7ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\48e.bmp: 480x768 1 cell, 67.4ms
Speed: 4.5ms preprocess, 67.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\48f.bmp: 480x768 1 cell, 75.0ms
Speed: 5.2ms preprocess, 75.0ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 48f.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\49b.bmp: 480x768 1 cell, 62.5ms
Speed: 4.3ms preprocess, 62.5ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 49b.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\49c.bmp: 480x768 4 cells, 65.7ms
Speed: 4.0ms preprocess, 65.7ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\49d.bmp: 480x768 8 cells, 78.3ms
Speed: 3.7ms preprocess, 78.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\4b.bmp: 480x768 1 cell, 76.6ms
Speed: 3.6ms preprocess, 76.6ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\50b.bmp: 480x768 6 cells, 74.2ms
Speed: 4.6ms preprocess, 74.2ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\50c.bmp: 480x768 7 cells, 107.8ms
Speed: 5.9ms preprocess, 107.8ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\50d.bmp: 480x768 8 cells, 93.5ms
Speed: 3.6ms preprocess, 93.5ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\50e.bmp: 480x768 5 cells, 91.6ms
Speed: 4.5ms preprocess, 91.6ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\50f.bmp: 480x768 6 cells, 88.4ms
Speed: 3.1ms preprocess, 88.4ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\51b.bmp: 480x768 7 cells, 76.6ms
Speed: 4.9ms preprocess, 76.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\51c.bmp: 480x768 7 cells, 64.9ms
Speed: 4.7ms preprocess, 64.9ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\51d.bmp: 480x768 4 cells, 65.8ms
Speed: 3.5ms preprocess, 65.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\51e.bmp: 480x768 6 cells, 67.6ms
Speed: 3.2ms preprocess, 67.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow 40\51g.bmp: 480x768 11 cells, 72.8ms
Speed: 3.6ms preprocess, 72.8ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0


In [64]:
accuracy_n

             Method  Accuracy
0       Mean Vector  0.979866
1         Slide Max  0.966443
2  Weighted Average  0.979866

In [66]:
df_n.to_excel('NSIL_pow40.xlsx', index=False)

## pow 10

In [67]:
accuracy_h_10, df_h_10 = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10", "HSIL")

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\10a.bmp: 480x768 84 cells, 1 HSIL_group, 84.5ms
Speed: 2.9ms preprocess, 84.5ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 23 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 73 - wszystkie features równe 0
Pominięto komórkę 80 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\11a.bmp: 480x768 1 cell, 1 HSIL_group, 71.5ms
Speed: 4.0ms preprocess, 71.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\12a.bmp: 480x768 75 cells, 1 HSIL_group, 84.7ms
Speed: 3.4ms preprocess, 84.7ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\13a.bmp: 480x768 15 cells, 1 HSIL_group, 68.2ms
Speed: 4.7ms preprocess, 68.2ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\14a.bmp: 480x768 6 cells, 1 HSIL_group, 88.0ms
Speed: 3.1ms preprocess, 88.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\15a.bmp: 480x768 92 cells, 2 HSIL_groups, 72.2ms
Speed: 2.9ms preprocess, 72.2ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 57 - wszystkie features równe 0
Pominięto komórkę 58 - wszystkie features równe 0
Pominięto komórkę 81 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\16a.bmp: 480x768 7 cells, 1 HSIL_group, 71.2ms
Speed: 3.1ms preprocess, 71.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\17a.bmp: 480x768 9 cells, 1 HSIL_group, 68.4ms
Speed: 3.5ms preprocess, 68.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\18a.bmp: 480x768 8 cells, 64.8ms
Speed: 4.3ms preprocess, 64.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\19a.bmp: 480x768 11 cells, 2 HSIL_groups, 63.9ms
Speed: 4.8ms preprocess, 63.9ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\1a.bmp: 480x768 9 cells, 2 HSIL_groups, 64.8ms
Speed: 4.8ms preprocess, 64.8ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\20a.bmp: 480x768 12 cells, 2 HSIL_groups, 70.4ms
Speed: 3.4ms preprocess, 70.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\21a.bmp: 480x768 29 cells, 72.1ms
Speed: 4.5ms preprocess, 72.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\22a.bmp: 480x768 8 cells, 76.9ms
Speed: 3.0ms preprocess, 76.9ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\23a.bmp: 480x768 55 cells, 64.3ms
Speed: 3.4ms preprocess, 64.3ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 33 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\24a.jpg: 480x768 4 cells, 67.2ms
Speed: 3.1ms preprocess, 67.2ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\25a.bmp: 480x768 8 cells, 2 HSIL_groups, 67.0ms
Speed: 3.2ms preprocess, 67.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\26a.bmp: 480x768 5 cells, 66.5ms
Speed: 4.6ms preprocess, 66.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\27a.bmp: 480x768 2 cells, 68.4ms
Speed: 3.6ms preprocess, 68.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\28a.bmp: 480x768 2 cells, 4 HSIL_groups, 69.9ms
Speed: 4.1ms preprocess, 69.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\29a.bmp: 480x768 8 cells, 1 HSIL_group, 62.0ms
Speed: 4.4ms preprocess, 62.0ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\2a.bmp: 480x768 8 cells, 2 HSIL_groups, 73.1ms
Speed: 3.4ms preprocess, 73.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\30a.bmp: 480x768 11 cells, 63.1ms
Speed: 3.3ms preprocess, 63.1ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\31a.bmp: 480x768 9 cells, 1 HSIL_group, 62.6ms
Speed: 3.0ms preprocess, 62.6ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\32a.bmp: 480x768 9 cells, 66.5ms
Speed: 3.4ms preprocess, 66.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\33a.bmp: 480x768 10 cells, 71.1ms
Speed: 3.3ms preprocess, 71.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\34a.bmp: 480x768 89 cells, 8 HSIL_groups, 66.3ms
Speed: 3.2ms preprocess, 66.3ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\35a.bmp: 480x768 62 cells, 68.3ms
Speed: 3.3ms preprocess, 68.3ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\36a.bmp: 480x768 45 cells, 71.3ms
Speed: 4.9ms preprocess, 71.3ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\37a.bmp: 480x768 75 cells, 67.3ms
Speed: 3.3ms preprocess, 67.3ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0
Pominięto komórkę 62 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0
Pominięto komórkę 69 - wszystkie features równe 0
Pominięto komórkę 71 - wszystkie features równe 0
Pominięto komórkę 72 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\38a.bmp: 480x768 43 cells, 2 HSIL_groups, 71.2ms
Speed: 5.6ms preprocess, 71.2ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\39a.bmp: 480x768 47 cells, 68.0ms
Speed: 4.4ms preprocess, 68.0ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\3a.bmp: 480x768 5 cells, 78.5ms
Speed: 5.8ms preprocess, 78.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\40a.bmp: 480x768 70 cells, 2 HSIL_groups, 69.0ms
Speed: 3.0ms preprocess, 69.0ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 48 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0
Pominięto komórkę 55 - wszystkie features równe 0
Pominięto komórkę 60 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\41a.bmp: 480x768 59 cells, 75.7ms
Speed: 4.3ms preprocess, 75.7ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\42a.bmp: 480x768 65 cells, 81.1ms
Speed: 5.8ms preprocess, 81.1ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 55 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 58 - wszystkie features równe 0
Pominięto komórkę 59 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0
Pominięto komórkę 62 - wszystkie features równe 0
Pominięto komórkę 63 - wszystkie features równe 0
Pominięto komórkę 64 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\43a.bmp: 480x768 61 cells, 91.9ms
Speed: 4.6ms preprocess, 91.9ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 47 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\44a.bmp: 480x768 50 cells, 76.4ms
Speed: 5.0ms preprocess, 76.4ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\45a.bmp: 480x768 38 cells, 70.9ms
Speed: 3.5ms preprocess, 70.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 33 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\46a.bmp: 480x768 49 cells, 77.7ms
Speed: 5.3ms preprocess, 77.7ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\47a.bmp: 480x768 31 cells, 95.6ms
Speed: 3.6ms preprocess, 95.6ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 23 - wszystkie features równe 0
Pominięto komórkę 25 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\48a.bmp: 480x768 34 cells, 1 HSIL_group, 83.0ms
Speed: 3.7ms preprocess, 83.0ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\49a.bmp: 480x768 30 cells, 2 HSIL_groups, 74.7ms
Speed: 3.5ms preprocess, 74.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\4a.bmp: 480x768 10 cells, 1 HSIL_group, 67.3ms
Speed: 3.2ms preprocess, 67.3ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\50a.bmp: 480x768 52 cells, 1 HSIL_group, 65.4ms
Speed: 2.9ms preprocess, 65.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\HSIL\pow 10\51a.bmp: 480x768 65 cells, 2 HSIL_groups, 74.4ms
Speed: 4.5ms preprocess, 74.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0

In [69]:
accuracy_h_10

             Method  Accuracy
0       Mean Vector  0.322581
1         Slide Max  0.258065
2  Weighted Average  0.322581

In [68]:
df_h_10

,Filename,True Class,Predicted Class_Mean,Mean Vector,Predicted Class_Max,Max Vector,Predicted Class_Weighted,Weight Vector,Probs
0,10a.bmp,HSIL,HSIL,"[0.5227542476937705, 0.1174510408801949, 0.359...",NSIL,"[0.9960459870009604, 0.9778753189343549, 0.996...",HSIL,"[0.5253506170486192, 0.10207956648632621, 0.37...","[[0.0020183341409103026, 0.0027077560600981885..."
1,11a.bmp,HSIL,HSIL,"[0.9973314773855628, 0.0010005094993395967, 0....",HSIL,"[0.9973314773855628, 0.0010005094993395967, 0....",HSIL,"[0.9973314773855628, 0.0010005094993395967, 0....","[[0.9973314773855628, 0.0010005094993395967, 0..."
2,12a.bmp,HSIL,NSIL,"[0.3121626876131099, 0.16006808486262494, 0.52...",NSIL,"[0.9968947384554893, 0.9593551695462026, 0.996...",NSIL,"[0.29400672055990973, 0.1413113080639338, 0.56...","[[0.0020317593225116573, 0.0027370758193978792..."
3,13a.bmp,HSIL,LSIL,"[0.17363059822626253, 0.7881723437199007, 0.03...",LSIL,"[0.8442267014510018, 0.9959362996601453, 0.214...",LSIL,"[0.14166682614185197, 0.8250205207680229, 0.03...","[[0.022327821993147312, 0.7636228234763742, 0...."
4,14a.bmp,HSIL,NSIL,"[0.3416227433667219, 0.055184947917273186, 0.6...",NSIL,"[0.9728497217879941, 0.12571734147490218, 0.99...",NSIL,"[0.3323152495780874, 0.04779886793446786, 0.61...","[[0.5728758573786022, 0.12571734147490218, 0.3..."
...,...,...,...,...,...,...,...,...,...
57,63a.bmp,HSIL,LSIL,"[0.3439259938129396, 0.35579326182462623, 0.30...",LSIL,"[0.9972525889146941, 0.9979969953792543, 0.978...",HSIL,"[0.35401832412565715, 0.34923855403773824, 0.2...","[[0.0325791284224904, 0.40983630889710376, 0.5..."
58,6a.bmp,HSIL,HSIL,"[0.5747537525146331, 0.19225271713609673, 0.23...",HSIL,"[0.9742814562224982, 0.9062253033106684, 0.807...",HSIL,"[0.6102719820449426, 0.18868130023647878, 0.20...","[[0.1310679434197145, 0.21703796197955366, 0.6..."
59,7a.bmp,HSIL,NSIL,"[0.32331789615041906, 0.06947656015614005, 0.6...",NSIL,"[0.9292001960830063, 0.26389209210942893, 0.99...",NSIL,"[0.29303027733975434, 0.05584225336336577, 0.6...","[[0.002011131207089998, 0.002612525007487855, ..."
60,8a.bmp,HSIL,HSIL,"[0.7487135744176706, 0.06150360994356207, 0.18...",HSIL,"[0.9390603424719104, 0.14363230954180486, 0.59...",HSIL,"[0.7961614519139161, 0.05354694190586874, 0.15...","[[0.8603073670541972, 0.041532249570650236, 0...."
61,9a.bmp,HSIL,NSIL,"[0.39655282497756433, 0.10634411257764396, 0.4...",NSIL,"[0.9860601626320225, 0.7672052780720714, 0.996...",NSIL,"[0.3848571092074531, 0.0863536631835733, 0.528...","[[0.004757349115314478, 0.023020669857845424, ..."

In [70]:
accuracy_l_10, df_l_10 = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10", "LSIL")
print(accuracy_l_10)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\10a.bmp: 480x768 3 cells, 113.1ms
Speed: 3.1ms preprocess, 113.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\11a.bmp: 480x768 80 cells, 4 HSIL_groups, 93.8ms
Speed: 3.3ms preprocess, 93.8ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 63 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\13a.bmp: 480x768 47 cells, 79.2ms
Speed: 4.6ms preprocess, 79.2ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\14a.bmp: 480x768 64 cells, 129.1ms
Speed: 6.8ms preprocess, 129.1ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 23 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0
Pominięto komórkę 48 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 59 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\14a.jpg: 480x768 60 cells, 79.0ms
Speed: 3.6ms preprocess, 79.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 47 - wszystkie features równe 0
Pominięto komórkę 48 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0
Pominięto komórkę 55 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\15a.bmp: 480x768 61 cells, 75.3ms
Speed: 3.7ms preprocess, 75.3ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 47 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 58 - wszystkie features równe 0
Pominięto komórkę 59 - wszystkie features równe 0
Pominięto komórkę 60 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\17a.bmp: 480x768 51 cells, 81.9ms
Speed: 3.6ms preprocess, 81.9ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\1a.bmp: 480x768 23 cells, 70.6ms
Speed: 4.3ms preprocess, 70.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\20a.bmp: 480x768 48 cells, 1 HSIL_group, 65.5ms
Speed: 3.0ms preprocess, 65.5ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 26 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\21a.bmp: 480x768 55 cells, 85.2ms
Speed: 3.6ms preprocess, 85.2ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 15 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 25 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\22a.bmp: 480x768 54 cells, 80.8ms
Speed: 3.0ms preprocess, 80.8ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\23a.bmp: 480x768 52 cells, 68.2ms
Speed: 3.1ms preprocess, 68.2ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 23 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 33 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\24a.bmp: 480x768 47 cells, 1 HSIL_group, 70.5ms
Speed: 3.1ms preprocess, 70.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 33 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\25a.bmp: 480x768 25 cells, 3 HSIL_groups, 63.4ms
Speed: 3.5ms preprocess, 63.4ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\26a.bmp: 480x768 12 cells, 67.6ms
Speed: 4.2ms preprocess, 67.6ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\27a.bmp: 480x768 32 cells, 1 HSIL_group, 71.5ms
Speed: 3.5ms preprocess, 71.5ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 26 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\28a.bmp: 480x768 53 cells, 1 HSIL_group, 68.7ms
Speed: 3.5ms preprocess, 68.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 25 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\29a.bmp: 480x768 64 cells, 1 HSIL_group, 69.7ms
Speed: 3.5ms preprocess, 69.7ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 60 - wszystkie features równe 0
Pominięto komórkę 63 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\2a.bmp: 480x768 33 cells, 1 HSIL_group, 76.9ms
Speed: 3.7ms preprocess, 76.9ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 26 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\30a.bmp: 480x768 56 cells, 77.0ms
Speed: 3.3ms preprocess, 77.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 25 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 47 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\31a.bmp: 480x768 33 cells, 90.4ms
Speed: 3.2ms preprocess, 90.4ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 14 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\32a.bmp: 480x768 8 cells, 1 HSIL_group, 73.5ms
Speed: 3.1ms preprocess, 73.5ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\33a.bmp: 480x768 10 cells, 84.4ms
Speed: 3.1ms preprocess, 84.4ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\34a.bmp: 480x768 17 cells, 2 HSIL_groups, 73.5ms
Speed: 3.5ms preprocess, 73.5ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\3a.bmp: 480x768 55 cells, 75.7ms
Speed: 3.1ms preprocess, 75.7ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\4a.bmp: 480x768 39 cells, 64.1ms
Speed: 3.7ms preprocess, 64.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\6a.bmp: 480x768 22 cells, 70.0ms
Speed: 4.4ms preprocess, 70.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\7a.bmp: 480x768 44 cells, 1 HSIL_group, 76.3ms
Speed: 2.9ms preprocess, 76.3ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\8a.bmp: 480x768 7 cells, 1 HSIL_group, 81.4ms
Speed: 3.4ms preprocess, 81.4ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\LSIL\pow. 10\9a.bmp: 480x768 11 cells, 1 HSIL_group, 72.7ms
Speed: 4.7ms preprocess, 72.7ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)
             Method  Accuracy
0       Mean Vector  0.366667
1         Slide Max  0.266667
2  Weighted Average  0.333333

In [71]:
accuracy_n_10, df_n_10 = get_metric(r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10", "NSIL")
print(accuracy_n_10)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\10a.bmp: 480x768 35 cells, 2 HSIL_groups, 87.1ms
Speed: 3.6ms preprocess, 87.1ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 29 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\11a.bmp: 480x768 2 cells, 67.3ms
Speed: 3.9ms preprocess, 67.3ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\12a.bmp: 480x768 2 cells, 66.6ms
Speed: 3.3ms preprocess, 66.6ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\13a.bmp: 480x768 12 cells, 67.2ms
Speed: 3.7ms preprocess, 67.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\14a.bmp: 480x768 2 cells, 86.4ms
Speed: 6.0ms preprocess, 86.4ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\15a.bmp: 480x768 6 cells, 74.7ms
Speed: 4.3ms preprocess, 74.7ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\16a.bmp: 480x768 8 cells, 65.2ms
Speed: 3.3ms preprocess, 65.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\17a.bmp: 480x768 7 cells, 62.8ms
Speed: 3.3ms preprocess, 62.8ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\18a.bmp: 480x768 18 cells, 61.3ms
Speed: 5.3ms preprocess, 61.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\19a.bmp: 480x768 19 cells, 67.4ms
Speed: 3.1ms preprocess, 67.4ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 15 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\1a.bmp: 480x768 4 cells, 78.9ms
Speed: 4.6ms preprocess, 78.9ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\20a.bmp: 480x768 5 cells, 65.1ms
Speed: 5.0ms preprocess, 65.1ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\21a.bmp: 480x768 2 cells, 65.4ms
Speed: 3.6ms preprocess, 65.4ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\22a.bmp: 480x768 19 cells, 61.6ms
Speed: 3.7ms preprocess, 61.6ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 11 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\23a.bmp: 480x768 1 cell, 62.3ms
Speed: 3.4ms preprocess, 62.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\24a.bmp: 480x768 1 cell, 63.9ms
Speed: 4.0ms preprocess, 63.9ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\25a.bmp: 480x768 8 cells, 90.8ms
Speed: 3.3ms preprocess, 90.8ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\26a.bmp: 480x768 2 cells, 58.1ms
Speed: 5.2ms preprocess, 58.1ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\27a.bmp: 768x480 8 cells, 68.8ms
Speed: 3.4ms preprocess, 68.8ms inference, 2.1ms postprocess per image at shape (1, 3, 768, 480)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\28a.bmp: 480x768 2 cells, 64.1ms
Speed: 3.4ms preprocess, 64.1ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\29a.bmp: 480x768 4 cells, 69.7ms
Speed: 4.5ms preprocess, 69.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\2a.bmp: 480x768 7 cells, 79.9ms
Speed: 3.6ms preprocess, 79.9ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\30a.bmp: 480x768 3 cells, 66.5ms
Speed: 2.9ms preprocess, 66.5ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\31a.bmp: 480x768 2 cells, 61.6ms
Speed: 5.7ms preprocess, 61.6ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\32a.bmp: 480x768 2 cells, 67.1ms
Speed: 4.0ms preprocess, 67.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\33a.bmp: 480x768 7 cells, 62.7ms
Speed: 4.2ms preprocess, 62.7ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\34a.bmp: 480x768 45 cells, 68.6ms
Speed: 4.8ms preprocess, 68.6ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\35a.bmp: 480x768 3 cells, 72.1ms
Speed: 3.7ms preprocess, 72.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\36a.bmp: 480x768 8 cells, 64.0ms
Speed: 5.0ms preprocess, 64.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\37a.bmp: 480x768 2 cells, 64.2ms
Speed: 3.1ms preprocess, 64.2ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\38a.bmp: 480x768 1 cell, 63.0ms
Speed: 5.0ms preprocess, 63.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\39a.bmp: 480x768 3 cells, 63.3ms
Speed: 3.3ms preprocess, 63.3ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\3a.bmp: 480x768 18 cells, 1 HSIL_group, 67.4ms
Speed: 4.0ms preprocess, 67.4ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\40a.bmp: 480x768 4 cells, 65.7ms
Speed: 3.2ms preprocess, 65.7ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\41a.bmp: 480x768 3 cells, 68.7ms
Speed: 3.6ms preprocess, 68.7ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\42a.bmp: 480x768 5 cells, 71.5ms
Speed: 3.5ms preprocess, 71.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\43a.bmp: 480x768 31 cells, 2 HSIL_groups, 81.5ms
Speed: 3.3ms preprocess, 81.5ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 26 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\44a.bmp: 480x768 45 cells, 1 HSIL_group, 65.2ms
Speed: 3.3ms preprocess, 65.2ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0
Pominięto komórkę 15 - wszystkie features równe 0
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\45a.bmp: 480x768 1 cell, 83.9ms
Speed: 3.9ms preprocess, 83.9ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
⚠️ Warning: No cells detected in 45a.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\46a.bmp: 480x768 3 cells, 80.1ms
Speed: 4.1ms preprocess, 80.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 1 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0
⚠️ Warning: No cells detected in 46a.bmp - skipping

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\47a.bmp: 480x768 4 cells, 78.6ms
Speed: 4.1ms preprocess, 78.6ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\48a.bmp: 480x768 5 cells, 64.7ms
Speed: 3.4ms preprocess, 64.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\49a.bmp: 512x768 21 cells, 68.0ms
Speed: 3.4ms preprocess, 68.0ms inference, 2.2ms postprocess per image at shape (1, 3, 512, 768)
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\4a.bmp: 480x768 20 cells, 71.4ms
Speed: 3.1ms preprocess, 71.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 16 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\50a.bmp: 480x768 68 cells, 1 HSIL_group, 69.5ms
Speed: 3.5ms preprocess, 69.5ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 33 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 55 - wszystkie features równe 0
Pominięto komórkę 63 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0
Pominięto komórkę 68 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\51a.bmp: 480x768 69 cells, 67.7ms
Speed: 3.6ms preprocess, 67.7ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 57 - wszystkie features równe 0
Pominięto komórkę 62 - wszystkie features równe 0
Pominięto komórkę 64 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\52a.bmp: 480x768 102 cells, 67.0ms
Speed: 4.8ms preprocess, 67.0ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0
Pominięto komórkę 67 - wszystkie features równe 0
Pominięto komórkę 68 - wszystkie features równe 0
Pominięto komórkę 70 - wszystkie features równe 0
Pominięto komórkę 74 - wszystkie features równe 0
Pominięto komórkę 75 - wszystkie features równe 0
Pominięto komórkę 76 - wszystkie features równe 0
Pominięto komórkę 90 - wszystkie features równe 0
Pominięto komórkę 94 - wszystkie features równe 0
Pominięto komórkę 97 - wszystkie features równe 0
Pominięto komórkę 99 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\53a.bmp: 480x768 54 cells, 71.0ms
Speed: 3.2ms preprocess, 71.0ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 33 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\54a.bmp: 480x768 24 cells, 74.1ms
Speed: 3.7ms preprocess, 74.1ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 11 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\55a.bmp: 480x768 40 cells, 1 HSIL_group, 81.6ms
Speed: 5.8ms preprocess, 81.6ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 26 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\56a.bmp: 768x480 36 cells, 68.0ms
Speed: 3.2ms preprocess, 68.0ms inference, 2.3ms postprocess per image at shape (1, 3, 768, 480)
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\57a.bmp: 480x768 42 cells, 63.0ms
Speed: 5.0ms preprocess, 63.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\58a.bmp: 480x768 4 cells, 69.6ms
Speed: 4.0ms preprocess, 69.6ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\59a.bmp: 480x768 71 cells, 75.9ms
Speed: 3.9ms preprocess, 75.9ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\5a.bmp: 480x768 6 cells, 78.5ms
Speed: 3.7ms preprocess, 78.5ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\60a.bmp: 480x768 44 cells, 79.1ms
Speed: 3.5ms preprocess, 79.1ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 25 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\61a.bmp: 480x768 80 cells, 1 HSIL_group, 69.3ms
Speed: 3.7ms preprocess, 69.3ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 63 - wszystkie features równe 0
Pominięto komórkę 66 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\62a.bmp: 480x768 83 cells, 63.3ms
Speed: 3.8ms preprocess, 63.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\63a.bmp: 480x768 1 cell, 71.0ms
Speed: 3.8ms preprocess, 71.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\64a.bmp: 480x768 6 cells, 63.7ms
Speed: 3.6ms preprocess, 63.7ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\65a.bmp: 480x768 2 cells, 68.2ms
Speed: 4.0ms preprocess, 68.2ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\66a.bmp: 480x768 2 cells, 72.4ms
Speed: 3.7ms preprocess, 72.4ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides\NSIL\pow. 10\67a.bmp: 480x768 1 cell, 73.0ms
Speed: 3.3ms preprocess, 73.0ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 768)


## WAGI DLA HSIL

In [7]:
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (accuracy_score, f1_score, recall_score, 
                             precision_score, classification_report, confusion_matrix)
from itertools import product
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

In [8]:
def class_weighted_pooling(cell_probs, class_weights=[3.0, 1.5, 1.0], pooling='max'):
    if len(cell_probs) == 0:
        return None
    
    weighted_probs = cell_probs * np.array(class_weights)
    
    if pooling == 'max':
        slide_probs_weighted = np.max(weighted_probs, axis=0)
    elif pooling == 'mean':
        slide_probs_weighted = np.mean(weighted_probs, axis=0)
    else:
        raise ValueError(f"Unknown pooling: {pooling}")
    
    slide_probs = slide_probs_weighted / slide_probs_weighted.sum()
    return slide_probs

In [9]:
def load_cell_probabilities_from_folder(folder_path, class_name, class_to_idx):
    slides = []
    labels = []
    filenames = []
    
    if not os.path.exists(folder_path):
        print(f"⚠️  Folder nie istnieje: {folder_path}")
        return slides, labels, filenames
    
    files = [f for f in os.listdir(folder_path) if f.endswith(('.bmp'))]
    
    for filename in files:
        file_path = os.path.join(folder_path, filename)
        features_list, predicted_classed_fused, cell_probs, df_preds, bbox_image_path, crop_pat = get_info(file_path, show_image=False)

        if len(cell_probs) == 0:
                print(f"⚠️  Brak komórek w {filename}, pomijam...")
                continue
        slides.append(cell_probs)
        labels.append(class_to_idx[class_name])
        filenames.append(filename)
            
    return slides, labels, filenames

In [10]:
def load_all_data(base_path, class_names):

    class_to_idx = {name: idx for idx, name in enumerate(class_names)}
    
    train_slides, train_labels, train_files = [], [], []
    test_slides, test_labels, test_files = [], [], []
    
    # Wczytaj train
    print("\n📂 Wczytuję dane treningowe...")
    train_path = os.path.join(base_path, 'train')
    for class_name in class_names:
        folder_path = os.path.join(train_path, class_name)
        slides, labels, files = load_cell_probabilities_from_folder(
            folder_path, class_name, class_to_idx
        )
        train_slides.extend(slides)
        train_labels.extend(labels)
        train_files.extend(files)
        print(f"  {class_name}: {len(slides)} slajdów")
    
    # Wczytaj test
    print("\n📂 Wczytuję dane testowe...")
    test_path = os.path.join(base_path, 'test')
    for class_name in class_names:
        folder_path = os.path.join(test_path, class_name)
        slides, labels, files = load_cell_probabilities_from_folder(
            folder_path, class_name, class_to_idx
        )
        test_slides.extend(slides)
        test_labels.extend(labels)
        test_files.extend(files)
        print(f"  {class_name}: {len(slides)} slajdów")
    
    train_data = {
        'slides': train_slides,
        'labels': np.array(train_labels),
        'filenames': train_files
    }
    
    test_data = {
        'slides': test_slides,
        'labels': np.array(test_labels),
        'filenames': test_files
    }
    
    print(f"\n✓ Wczytano:")
    print(f"  Train: {len(train_slides)} slajdów")
    print(f"  Test: {len(test_slides)} slajdów")
    
    return train_data, test_data

In [11]:
def calculate_metrics(y_true, y_pred, class_names):
    """Oblicz wszystkie metryki"""
    acc = accuracy_score(y_true, y_pred)
    f1_macro = f1_score(y_true, y_pred, average='macro', zero_division=0)
    
    # Recall per class
    recall_per_class = recall_score(y_true, y_pred, labels=[0, 1, 2], 
                                    average=None, zero_division=0)
    
    hsil_recall = recall_per_class[0] if len(recall_per_class) > 2 else 0.0
    
    return {
        'accuracy': acc,
        'f1_macro': f1_macro,
        'hsil_recall': hsil_recall,
        'recall_per_class': recall_per_class
    }

In [12]:
def cross_validated_weight_search(train_data, class_names, n_splits=5):
    """
    K-fold Cross-Validation Grid Search dla wag klas i metod poolingu
    
    Testuje zarówno MAX jak i MEAN pooling
    
    Args:
        train_data: dict z 'slides' i 'labels'
        class_names: lista nazw klas ['NILM', 'LSIL', 'HSIL']
        n_splits: liczba foldów w CV
    
    Returns:
        best_config: dict z najlepszą konfiguracją (weights + pooling)
        results_df: DataFrame z wszystkimi wynikami
    """
    print("\n" + "="*70)
    print("CROSS-VALIDATION GRID SEARCH - MAX vs MEAN POOLING")
    print("="*70)
    
    # Przestrzeń przeszukiwania wag
    # UWAGA: Wagi w kolejności [w_HSIL, w_LSIL, w_NILM]
    hsil_weights = [2.0, 3.0, 4.0, 5.0, 7.0]
    lsil_weights = [1.0, 1.5, 2.0, 2.5, 3.0]
    nilm_weights = [1.0]  # NILM bazowy
    
    pooling_methods = ['max', 'mean']
    
    all_combinations = list(product(hsil_weights, lsil_weights, nilm_weights, pooling_methods))
    print(f"\nLiczba kombinacji do przetestowania: {len(all_combinations)}")
    print(f"  - Metody poolingu: {pooling_methods}")
    print(f"  - Wagi HSIL: {hsil_weights}")
    print(f"  - Wagi LSIL: {lsil_weights}")
    print(f"  - Wagi NILM: {nilm_weights}")
    print(f"\nFolds: {n_splits}")
    print(f"Łącznie ewaluacji: {len(all_combinations) * n_splits}")
    
    # K-fold split
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    
    results = []
    
    # Grid search
    for w_hsil, w_lsil, w_nilm, pooling in tqdm(all_combinations, desc="Grid Search"):
        class_weights = [w_hsil, w_lsil, w_nilm]  # [HSIL, LSIL, NILM]
        
        fold_metrics = {
            'accuracy': [],
            'f1_macro': [],
            'hsil_recall': []
        }
        
        # Cross-validation
        for fold_idx, (train_idx, val_idx) in enumerate(skf.split(train_data['slides'], 
                                                                   train_data['labels'])):
            # Split data
            val_slides = [train_data['slides'][i] for i in val_idx]
            val_labels = train_data['labels'][val_idx]
            
            # Predykcje na walidacji
            val_preds = []
            for cell_probs in val_slides:
                slide_probs = class_weighted_pooling(cell_probs, class_weights, pooling)
                if slide_probs is not None:
                    val_preds.append(np.argmax(slide_probs))
                else:
                    val_preds.append(2)  
            
            val_preds = np.array(val_preds)
            
            # Metryki
            metrics = calculate_metrics(val_labels, val_preds, class_names)
            
            fold_metrics['accuracy'].append(metrics['accuracy'])
            fold_metrics['f1_macro'].append(metrics['f1_macro'])
            fold_metrics['hsil_recall'].append(metrics['hsil_recall'])
        
        # Średnia i odchylenie standardowe z foldów
        results.append({
            'pooling': pooling,
            'w_hsil': w_hsil,
            'w_lsil': w_lsil,
            'w_nilm': w_nilm,
            'weights': class_weights,
            'mean_accuracy': np.mean(fold_metrics['accuracy']),
            'std_accuracy': np.std(fold_metrics['accuracy']),
            'mean_f1': np.mean(fold_metrics['f1_macro']),
            'std_f1': np.std(fold_metrics['f1_macro']),
            'mean_hsil_recall': np.mean(fold_metrics['hsil_recall']),
            'std_hsil_recall': np.std(fold_metrics['hsil_recall']),

        })
    
    # Stwórz DataFrame z wynikami
    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values('mean_f1', ascending=False)
    
    # Najlepsza konfiguracja
    best = results_df.iloc[0]
    best_config = {
        'pooling': best['pooling'],
        'weights': [best['w_hsil'], best['w_lsil'], best['w_nilm']],
        'metrics': {
            'accuracy': best['mean_accuracy'],
            'f1_macro': best['mean_f1'],
            'hsil_recall': best['mean_hsil_recall'],
        }
    }
    
    # Wyświetl wyniki
    print("\n" + "="*70)
    print("WYNIKI")
    print("="*70)
    print(f"\n🏆 NAJLEPSZA KONFIGURACJA:")
    print(f"  Pooling: {best['pooling'].upper()}")
    print(f"  Wagi [HSIL, LSIL, NILM]: {best_config['weights']}")
    print(f"\nMetryki (średnia ± std z {n_splits} foldów):")
    print(f"  Accuracy:     {best['mean_accuracy']:.4f} ± {best['std_accuracy']:.4f}")
    print(f"  F1 Macro:     {best['mean_f1']:.4f} ± {best['std_f1']:.4f}")
    print(f"  HSIL Recall:  {best['mean_hsil_recall']:.4f} ± {best['std_hsil_recall']:.4f}")
    
    print(f"\n📊 Top 10 konfiguracji:")
    print(results_df.head(10)[['pooling', 'weights', 'mean_accuracy', 'mean_f1', 
                                'mean_hsil_recall']])
    
    # Porównanie MAX vs MEAN
    print(f"\n📊 Porównanie MAX vs MEAN (najlepsze wyniki):")
    for pooling_method in ['max', 'mean']:
        best_for_method = results_df[results_df['pooling'] == pooling_method].iloc[0]
        print(f"\n  {pooling_method.upper()}:")
        print(f"    Wagi: {[best_for_method['w_hsil'], best_for_method['w_lsil'], best_for_method['w_nilm']]}")
        print(f"    HSIL Recall:  {best_for_method['mean_hsil_recall']:.4f}")
        print(f"    Accuracy:     {best_for_method['mean_accuracy']:.4f}")
    
    return best_config, results_df

In [ ]:
BASE_PATH = r"C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset"
CLASS_NAMES = ['HSIL', 'LSIL', 'NSIL']  # Dla etykiet i nazw folderów
N_SPLITS = 5  # liczba foldów w CV
    
print("="*70)
print("OPTYMALIZACJA WAG + PORÓWNANIE MAX vs MEAN POOLING")
print("="*70)
print(f"\nŚcieżka bazowa: {BASE_PATH}")
print(f"Klasy: {CLASS_NAMES}")
print(f"\n⚠️  UWAGA: Format prawdopodobieństw w plikach: [p_HSIL, p_LSIL, p_NSIL]")
    
# 1. Wczytaj dane
train_data, test_data = load_all_data(BASE_PATH, CLASS_NAMES)
    
if len(train_data['slides']) == 0:
    print("❌ Brak danych treningowych! Sprawdź ścieżki i format plików.")
    
    
# 2. Cross-validation grid search na train (MAX vs MEAN)
best_config, results_df = cross_validated_weight_search(
    train_data, CLASS_NAMES, n_splits=N_SPLITS
    )
    
# 3. Zapisz wyniki CV
results_df.to_csv('cv_grid_search_max_vs_mean.csv', index=False)
print(f"\n✓ Zapisano wyniki CV do: cv_grid_search_max_vs_mean_HSIL_LSIL_GROUP.csv")

======================================================================
OPTYMALIZACJA WAG + PORÓWNANIE MAX vs MEAN POOLING
======================================================================

Ścieżka bazowa: C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset
Klasy: ['HSIL', 'LSIL', 'NSIL']

⚠️  UWAGA: Format prawdopodobieństw w plikach: [p_HSIL, p_LSIL, p_NSIL]

📂 Wczytuję dane treningowe...

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\10a.bmp: 480x768 84 cells, 1 HSIL_group, 90.0ms
Speed: 3.7ms preprocess, 90.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 23 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 73 - wszystkie features równe 0
Pominięto komórkę 80 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\11a.bmp: 480x768 1 cell, 1 HSIL_group, 86.9ms
Speed: 3.2ms preprocess, 86.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\11b.bmp: 480x768 7 cells, 1 HSIL_group, 80.6ms
Speed: 3.3ms preprocess, 80.6ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\12a.bmp: 480x768 75 cells, 1 HSIL_group, 71.5ms
Speed: 3.4ms preprocess, 71.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\12b.bmp: 480x768 19 cells, 65.0ms
Speed: 3.3ms preprocess, 65.0ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\13a.bmp: 480x768 15 cells, 1 HSIL_group, 71.5ms
Speed: 3.3ms preprocess, 71.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\13b.bmp: 480x768 7 cells, 2 HSIL_groups, 69.8ms
Speed: 3.2ms preprocess, 69.8ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\14a.bmp: 480x768 6 cells, 1 HSIL_group, 65.5ms
Speed: 3.0ms preprocess, 65.5ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\15a.bmp: 480x768 92 cells, 2 HSIL_groups, 66.4ms
Speed: 3.4ms preprocess, 66.4ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 9 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0
Pominięto komórkę 29 - wszystkie features równe 0
Pominięto komórkę 34 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 57 - wszystkie features równe 0
Pominięto komórkę 58 - wszystkie features równe 0
Pominięto komórkę 81 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\15b.bmp: 480x768 15 cells, 2 HSIL_groups, 56.2ms
Speed: 2.9ms preprocess, 56.2ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\16a.bmp: 480x768 7 cells, 1 HSIL_group, 62.7ms
Speed: 3.5ms preprocess, 62.7ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\16b.bmp: 480x768 23 cells, 1 HSIL_group, 64.7ms
Speed: 3.3ms preprocess, 64.7ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\17a.bmp: 480x768 9 cells, 1 HSIL_group, 80.9ms
Speed: 4.2ms preprocess, 80.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\17b.bmp: 480x768 6 cells, 2 HSIL_groups, 62.7ms
Speed: 3.4ms preprocess, 62.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\18a.bmp: 480x768 8 cells, 58.9ms
Speed: 3.2ms preprocess, 58.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\19a.bmp: 480x768 11 cells, 2 HSIL_groups, 67.2ms
Speed: 3.5ms preprocess, 67.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\19b.bmp: 480x768 7 cells, 61.8ms
Speed: 3.8ms preprocess, 61.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\1a.bmp: 480x768 9 cells, 2 HSIL_groups, 59.0ms
Speed: 2.9ms preprocess, 59.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\1b.bmp: 480x768 10 cells, 1 HSIL_group, 57.9ms
Speed: 3.6ms preprocess, 57.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\20a.bmp: 480x768 12 cells, 2 HSIL_groups, 55.9ms
Speed: 4.8ms preprocess, 55.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\21a.bmp: 480x768 29 cells, 61.9ms
Speed: 3.4ms preprocess, 61.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 14 - wszystkie features równe 0
Pominięto komórkę 17 - wszystkie features równe 0
Pominięto komórkę 18 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\22a.bmp: 480x768 8 cells, 67.7ms
Speed: 3.2ms preprocess, 67.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\23b.bmp: 480x768 7 cells, 57.0ms
Speed: 3.0ms preprocess, 57.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 0 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\24b.bmp: 480x768 5 cells, 67.2ms
Speed: 3.3ms preprocess, 67.2ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\25b.bmp: 480x768 7 cells, 66.3ms
Speed: 3.2ms preprocess, 66.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\25c.bmp: 480x768 2 cells, 68.4ms
Speed: 4.0ms preprocess, 68.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\26a.bmp: 480x768 5 cells, 63.0ms
Speed: 4.5ms preprocess, 63.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\26b.bmp: 480x768 3 cells, 61.7ms
Speed: 3.2ms preprocess, 61.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\27a.bmp: 480x768 2 cells, 66.8ms
Speed: 3.3ms preprocess, 66.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\27b.bmp: 480x768 2 cells, 58.6ms
Speed: 3.0ms preprocess, 58.6ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\28a.bmp: 480x768 2 cells, 4 HSIL_groups, 71.7ms
Speed: 4.0ms preprocess, 71.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\29a.bmp: 480x768 8 cells, 1 HSIL_group, 62.4ms
Speed: 3.2ms preprocess, 62.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\2a.bmp: 480x768 8 cells, 2 HSIL_groups, 70.0ms
Speed: 3.3ms preprocess, 70.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\2b.bmp: 480x768 5 cells, 66.7ms
Speed: 3.2ms preprocess, 66.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 1 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\30a.bmp: 480x768 11 cells, 57.8ms
Speed: 4.4ms preprocess, 57.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\30b.bmp: 480x768 2 cells, 58.4ms
Speed: 3.3ms preprocess, 58.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\31a.bmp: 480x768 9 cells, 1 HSIL_group, 63.3ms
Speed: 3.5ms preprocess, 63.3ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\31b.bmp: 480x768 3 cells, 64.4ms
Speed: 3.1ms preprocess, 64.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\32a.bmp: 480x768 9 cells, 56.9ms
Speed: 3.2ms preprocess, 56.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\32b.bmp: 480x768 1 cell, 61.4ms
Speed: 3.1ms preprocess, 61.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\33a.bmp: 480x768 10 cells, 54.4ms
Speed: 3.6ms preprocess, 54.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\33b.bmp: 480x768 5 cells, 1 HSIL_group, 54.6ms
Speed: 2.9ms preprocess, 54.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\34a.bmp: 480x768 89 cells, 8 HSIL_groups, 59.4ms
Speed: 2.5ms preprocess, 59.4ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\34b.bmp: 480x768 10 cells, 70.2ms
Speed: 3.3ms preprocess, 70.2ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 8 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\35a.bmp: 480x768 62 cells, 62.9ms
Speed: 2.9ms preprocess, 62.9ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 16 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 37 - wszystkie features równe 0
Pominięto komórkę 40 - wszystkie features równe 0
Pominięto komórkę 42 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\36b.bmp: 480x768 2 cells, 80.2ms
Speed: 3.2ms preprocess, 80.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\37a.bmp: 480x768 75 cells, 69.4ms
Speed: 3.3ms preprocess, 69.4ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 13 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 53 - wszystkie features równe 0
Pominięto komórkę 54 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0
Pominięto komórkę 62 - wszystkie features równe 0
Pominięto komórkę 65 - wszystkie features równe 0
Pominięto komórkę 69 - wszystkie features równe 0
Pominięto komórkę 71 - wszystkie features równe 0
Pominięto komórkę 72 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\37b.bmp: 480x768 6 cells, 61.0ms
Speed: 5.1ms preprocess, 61.0ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\38a.bmp: 480x768 43 cells, 2 HSIL_groups, 73.3ms
Speed: 3.2ms preprocess, 73.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 12 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\39a.bmp: 480x768 47 cells, 66.6ms
Speed: 3.0ms preprocess, 66.6ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 2 - wszystkie features równe 0
Pominięto komórkę 5 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 28 - wszystkie features równe 0
Pominięto komórkę 36 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 39 - wszystkie features równe 0
Pominięto komórkę 41 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\39b.bmp: 480x768 5 cells, 59.1ms
Speed: 4.4ms preprocess, 59.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\3a.bmp: 480x768 5 cells, 64.6ms
Speed: 3.7ms preprocess, 64.6ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\40b.bmp: 480x768 7 cells, 65.9ms
Speed: 3.1ms preprocess, 65.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\41a.bmp: 480x768 59 cells, 59.1ms
Speed: 3.9ms preprocess, 59.1ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 20 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\41b.bmp: 480x768 5 cells, 63.8ms
Speed: 3.4ms preprocess, 63.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 4 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\42a.bmp: 480x768 65 cells, 61.5ms
Speed: 3.9ms preprocess, 61.5ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 3 - wszystkie features równe 0
Pominięto komórkę 6 - wszystkie features równe 0
Pominięto komórkę 7 - wszystkie features równe 0
Pominięto komórkę 8 - wszystkie features równe 0
Pominięto komórkę 10 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 22 - wszystkie features równe 0
Pominięto komórkę 30 - wszystkie features równe 0
Pominięto komórkę 31 - wszystkie features równe 0
Pominięto komórkę 32 - wszystkie features równe 0
Pominięto komórkę 35 - wszystkie features równe 0
Pominięto komórkę 38 - wszystkie features równe 0
Pominięto komórkę 43 - wszystkie features równe 0
Pominięto komórkę 44 - wszystkie features równe 0
Pominięto komórkę 45 - wszystkie features równe 0
Pominięto komórkę 46 - wszystkie features równe 0
Pominięto komórkę 49 - wszystkie features równe 0
Pominięto komórkę 50 - wszystkie features równe 0
Pominięto komórkę 51 - wszystkie features równe 0
Pominięto komórkę 52 - wszystkie features równe 0
Pominięto komórkę 55 - wszystkie features równe 0
Pominięto komórkę 56 - wszystkie features równe 0
Pominięto komórkę 58 - wszystkie features równe 0
Pominięto komórkę 59 - wszystkie features równe 0
Pominięto komórkę 61 - wszystkie features równe 0
Pominięto komórkę 62 - wszystkie features równe 0
Pominięto komórkę 63 - wszystkie features równe 0
Pominięto komórkę 64 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\42b.bmp: 480x768 10 cells, 70.4ms
Speed: 3.4ms preprocess, 70.4ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 9 - wszystkie features równe 0

image 1/1 C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_dataset\train\HSIL\43a.bmp: 480x768 61 cells, 58.0ms
Speed: 2.9ms preprocess, 58.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 768)
Pominięto komórkę 19 - wszystkie features równe 0
Pominięto komórkę 21 - wszystkie features równe 0
Pominięto komórkę 24 - wszystkie features równe 0
Pominięto komórkę 27 - wszystkie features równe 0

Grid Search: 100%|██████████| 50/50 [00:00<00:00, 64.88it/s]

======================================================================
WYNIKI
======================================================================

🏆 NAJLEPSZA KONFIGURACJA:
  Pooling: MEAN
  Wagi [HSIL, LSIL, NILM]: [np.float64(3.0), np.float64(2.0), np.float64(1.0)]

Metryki (średnia ± std z 5 foldów):
  Accuracy:     0.8044 ± 0.0442
  F1 Macro:     0.7425 ± 0.0538
  HSIL Recall:  0.6668 ± 0.0803

📊 Top 10 konfiguracji:
   pooling          weights  mean_accuracy   mean_f1  mean_hsil_recall
15    mean  [3.0, 2.0, 1.0]       0.804429  0.742456          0.666842
5     mean  [2.0, 2.0, 1.0]       0.804382  0.738300          0.595789
17    mean  [3.0, 2.5, 1.0]       0.795338  0.737988          0.646842
3     mean  [2.0, 1.5, 1.0]       0.804382  0.736750          0.626316
19    mean  [3.0, 3.0, 1.0]       0.783077  0.727384          0.616316
27    mean  [4.0, 2.5, 1.0]       0.776970  0.724486          0.666842
29    mean  [4.0, 3.0, 1.0]       0.770909  0.722414          0.656842
39    mean  [5.0, 3.0, 1.0]       0.767786  0.721598          0.686842
7     mean  [2.0, 2.5, 1.0]       0.782984  0.716353          0.535263
13    mean  [3.0, 1.5, 1.0]       0.792121  0.712406          0.697368

📊 Porównanie MAX vs MEAN (najlepsze wyniki):

  MAX:
    Wagi: [np.float64(2.0), np.float64(2.0), np.float64(1.0)]
    HSIL Recall:  0.5663
    Accuracy:     0.6789

  MEAN:
    Wagi: [np.float64(3.0), np.float64(2.0), np.float64(1.0)]
    HSIL Recall:  0.6668
    Accuracy:     0.8044

✓ Zapisano wyniki CV do: cv_grid_search_max_vs_mean.csv

In [14]:
results_df

,pooling,w_hsil,w_lsil,w_nilm,weights,mean_accuracy,std_accuracy,mean_f1,std_f1,mean_hsil_recall,std_hsil_recall
15,mean,3.0,2.0,1.0,"[3.0, 2.0, 1.0]",0.804429,0.044242,0.742456,0.053810,0.666842,0.080314
5,mean,2.0,2.0,1.0,"[2.0, 2.0, 1.0]",0.804382,0.037581,0.738300,0.050326,0.595789,0.071210
17,mean,3.0,2.5,1.0,"[3.0, 2.5, 1.0]",0.795338,0.050909,0.737988,0.061598,0.646842,0.098611
3,mean,2.0,1.5,1.0,"[2.0, 1.5, 1.0]",0.804382,0.033548,0.736750,0.048406,0.626316,0.080666
19,mean,3.0,3.0,1.0,"[3.0, 3.0, 1.0]",0.783077,0.048922,0.727384,0.056527,0.616316,0.086216
27,mean,4.0,2.5,1.0,"[4.0, 2.5, 1.0]",0.776970,0.041707,0.724486,0.049305,0.666842,0.080314
29,mean,4.0,3.0,1.0,"[4.0, 3.0, 1.0]",0.770909,0.050912,0.722414,0.061135,0.656842,0.084778
39,mean,5.0,3.0,1.0,"[5.0, 3.0, 1.0]",0.767786,0.043747,0.721598,0.052451,0.686842,0.096834
7,mean,2.0,2.5,1.0,"[2.0, 2.5, 1.0]",0.782984,0.028889,0.716353,0.034436,0.535263,0.058267
13,mean,3.0,1.5,1.0,"[3.0, 1.5, 1.0]",0.792121,0.039122,0.712406,0.055462,0.697368,0.098816
1,mean,2.0,1.0,1.0,"[2.0, 1.0, 1.0]",0.795105,0.024953,0.711922,0.042024,0.666842,0.097213
25,mean,4.0,2.0,1.0,"[4.0, 2.0, 1.0]",0.776876,0.041197,0.708122,0.056979,0.697368,0.098816
23,mean,4.0,1.5,1.0,"[4.0, 1.5, 1.0]",0.782937,0.047465,0.706956,0.071155,0.767368,0.052278
35,mean,5.0,2.0,1.0,"[5.0, 2.0, 1.0]",0.773800,0.048390,0.702441,0.072006,0.747368,0.083831
9,mean,2.0,3.0,1.0,"[2.0, 3.0, 1.0]",0.767739,0.028389,0.701121,0.030257,0.495263,0.060134
37,mean,5.0,2.5,1.0,"[5.0, 2.5, 1.0]",0.761632,0.038464,0.700684,0.046922,0.697368,0.098816
11,mean,3.0,1.0,1.0,"[3.0, 1.0, 1.0]",0.792121,0.039122,0.699067,0.061625,0.757368,0.049803
49,mean,7.0,3.0,1.0,"[7.0, 3.0, 1.0]",0.749417,0.059267,0.691463,0.071667,0.747368,0.083831
33,mean,5.0,1.5,1.0,"[5.0, 1.5, 1.0]",0.770723,0.043818,0.688517,0.069060,0.787895,0.037089
47,mean,7.0,2.5,1.0,"[7.0, 2.5, 1.0]",0.755571,0.059407,0.687708,0.079635,0.777895,0.050334
31,mean,5.0,1.0,1.0,"[5.0, 1.0, 1.0]",0.782890,0.034110,0.682821,0.069256,0.868947,0.039259
21,mean,4.0,1.0,1.0,"[4.0, 1.0, 1.0]",0.776783,0.043871,0.674913,0.078718,0.817895,0.026494
41,mean,7.0,1.0,1.0,"[7.0, 1.0, 1.0]",0.770723,0.046082,0.671134,0.076871,0.889474,0.057775
43,mean,7.0,1.5,1.0,"[7.0, 1.5, 1.0]",0.764569,0.046891,0.666239,0.075887,0.858947,0.036335
45,mean,7.0,2.0,1.0,"[7.0, 2.0, 1.0]",0.755431,0.062336,0.664548,0.095118,0.808421,0.047788
4,max,2.0,2.0,1.0,"[2.0, 2.0, 1.0]",0.678928,0.023292,0.639216,0.031101,0.566316,0.077877
18,max,3.0,3.0,1.0,"[3.0, 3.0, 1.0]",0.669837,0.033106,0.632549,0.040026,0.566316,0.077877
2,max,2.0,1.5,1.0,"[2.0, 1.5, 1.0]",0.724755,0.027390,0.627597,0.049818,0.950000,0.054772
0,max,2.0,1.0,1.0,"[2.0, 1.0, 1.0]",0.749184,0.028714,0.626222,0.048030,0.960000,0.037417
30,max,5.0,1.0,1.0,"[5.0, 1.0, 1.0]",0.737016,0.042317,0.618127,0.057819,0.960000,0.037417
20,max,4.0,1.0,1.0,"[4.0, 1.0, 1.0]",0.737016,0.042317,0.618127,0.057819,0.960000,0.037417
10,max,3.0,1.0,1.0,"[3.0, 1.0, 1.0]",0.737016,0.042317,0.618127,0.057819,0.960000,0.037417
28,max,4.0,3.0,1.0,"[4.0, 3.0, 1.0]",0.706480,0.042076,0.613623,0.061894,0.950000,0.054772
16,max,3.0,2.5,1.0,"[3.0, 2.5, 1.0]",0.700466,0.050613,0.612340,0.071203,0.920000,0.060000
40,max,7.0,1.0,1.0,"[7.0, 1.0, 1.0]",0.737063,0.048188,0.609047,0.080322,0.970000,0.040000
42,max,7.0,1.5,1.0,"[7.0, 1.5, 1.0]",0.709557,0.039137,0.607981,0.056164,0.960000,0.037417
22,max,4.0,1.5,1.0,"[4.0, 1.5, 1.0]",0.709557,0.039137,0.607981,0.056164,0.960000,0.037417
12,max,3.0,1.5,1.0,"[3.0, 1.5, 1.0]",0.709557,0.039137,0.607981,0.056164,0.960000,0.037417
32,max,5.0,1.5,1.0,"[5.0, 1.5, 1.0]",0.709557,0.039137,0.607981,0.056164,0.960000,0.037417
26,max,4.0,2.5,1.0,"[4.0, 2.5, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
34,max,5.0,2.0,1.0,"[5.0, 2.0, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
24,max,4.0,2.0,1.0,"[4.0, 2.0, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
38,max,5.0,3.0,1.0,"[5.0, 3.0, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
44,max,7.0,2.0,1.0,"[7.0, 2.0, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
46,max,7.0,2.5,1.0,"[7.0, 2.5, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
36,max,5.0,2.5,1.0,"[5.0, 2.5, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
48,max,7.0,3.0,1.0,"[7.0, 3.0, 1.0]",0.703450,0.039866,0.603099,0.057433,0.960000,0.037417
14,max,3.0,2.0,1.0,"[3.0, 2.0, 1.0]",0.703450,0.039866,0.602782,0.057653,0.960000,0.037417
6,max,2.0,2.5,1.0,"[2.0, 2.5, 1.0]",0.620746,0.021090,0.565598,0.018596,0.303158,0.055135
8,max,2.0,3.0,1.0,"[2.0, 3.0, 1.0]",0.617669,0.026551,0.562531,0.025305,0.292632,0.056720

In [ ]:
results_df.to_excel('cv_grid_search_max_vs_mean_HSIL_LSIL_GROUP.xlsx', index=False)

## Attention based slide classification

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os


class SlideDataset(Dataset):
    def __init__(self, data_dict):
        self.slides = data_dict['slides']
        self.labels = data_dict['labels']
        self.filenames = data_dict['filenames']
    
    def __len__(self):
        return len(self.slides)
    
    def __getitem__(self, idx):
        return torch.FloatTensor(self.slides[idx]), torch.LongTensor([self.labels[idx]])[0], self.filenames[idx]

class AttentionMIL(nn.Module):
    def __init__(self, input_dim=3, hidden_dim=128, num_classes=3, dropout=0.3):
        super(AttentionMIL, self).__init__()
        
        self.feature_extractor = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout)
        )
        
        self.attention = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.Tanh(),
            nn.Linear(hidden_dim // 2, 1)
        )
        
        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim // 2, num_classes)
        )
    
    def forward(self, x):
        # x shape: (batch_size, num_cells, input_dim)
        batch_size = x.shape[0]
        num_cells = x.shape[1]
        
        # Extract features z każdej komórki
        x_flat = x.view(-1, x.shape[2])
        features = self.feature_extractor(x_flat)
        features = features.view(batch_size, num_cells, -1)
        
        # Calculate attention weights
        attention_scores = self.attention(features)
        attention_weights = torch.softmax(attention_scores, dim=1)
        
        # Aggregate features using attention weights
        slide_features = torch.sum(attention_weights * features, dim=1)
        
        # Classify
        output = self.classifier(slide_features)
        
        return output, attention_weights

In [19]:
def collate_fn(batch):
    slides, labels, filenames = zip(*batch)
    
    # Znajdź maksymalną liczbę komórek w batch
    max_cells = max([s.shape[0] for s in slides])
    
    # Pad slajdy do tej samej długości
    padded_slides = []
    for slide in slides:
        num_cells = slide.shape[0]
        if num_cells < max_cells:
            padding = torch.zeros(max_cells - num_cells, slide.shape[1])
            padded_slide = torch.cat([slide, padding], dim=0)
        else:
            padded_slide = slide
        padded_slides.append(padded_slide)
    
    return torch.stack(padded_slides), torch.stack(labels), filenames

# Training function
def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0
    
    for slides, labels, _ in dataloader:
        slides, labels = slides.to(device), labels.to(device)
        
        optimizer.zero_grad()
        outputs, _ = model(slides)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    
    return total_loss / len(dataloader), 100 * correct / total

# Validation function
def validate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    
    with torch.no_grad():
        for slides, labels, _ in dataloader:
            slides, labels = slides.to(device), labels.to(device)
            
            outputs, _ = model(slides)
            loss = criterion(outputs, labels)
            
            total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    
    return total_loss / len(dataloader), 100 * correct / total

# Funkcja do ewaluacji z szczegółowymi metrykami
def evaluate_detailed(model, dataloader, device, class_names):
    model.eval()
    all_preds = []
    all_labels = []
    all_filenames = []
    
    with torch.no_grad():
        for slides, labels, filenames in dataloader:
            slides, labels = slides.to(device), labels.to(device)
            outputs, _ = model(slides)
            _, predicted = torch.max(outputs, 1)
            
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_filenames.extend(filenames)
    
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    
    # Confusion matrix
    from sklearn.metrics import confusion_matrix, classification_report
    
    cm = confusion_matrix(all_labels, all_preds)
    report = classification_report(all_labels, all_preds, target_names=class_names)
    
    print("\n📊 Confusion Matrix:")
    print(cm)
    print("\n📈 Classification Report:")
    print(report)
    
    # Błędnie sklasyfikowane próbki
    wrong_indices = np.where(all_preds != all_labels)[0]
    if len(wrong_indices) > 0:
        print(f"\n❌ Błędnie sklasyfikowane ({len(wrong_indices)} próbek):")
        for idx in wrong_indices[:10]:  # pokaż pierwsze 10
            print(f"  {all_filenames[idx]}: True={class_names[all_labels[idx]]}, Pred={class_names[all_preds[idx]]}")
    
    return all_preds, all_labels, all_filenames

# Funkcja do wizualizacji attention weights
def visualize_attention(model, slide, filename, device, class_names):
    model.eval()
    with torch.no_grad():
        slide_tensor = torch.FloatTensor(slide).unsqueeze(0).to(device)
        output, attention_weights = model(slide_tensor)
        
        _, predicted = torch.max(output, 1)
        attn = attention_weights.squeeze().cpu().numpy()
        
        print(f"\n🔍 Analiza slajdu: {filename}")
        print(f"  Predicted class: {class_names[predicted.item()]}")
        print(f"  Top 5 important cells (attention weights):")
        top_indices = np.argsort(attn.flatten())[-5:][::-1]
        for i, idx in enumerate(top_indices):
            if idx < len(slide):
                print(f"    Cell {idx}: weight={attn[idx]:.4f}, probs={slide[idx]}")
        
        return predicted.item(), attn

In [43]:
import numpy as np  # <--- DODANE (jeśli nie masz)
from torch.utils.data import DataLoader, WeightedRandomSampler  # <--- DODANE (import samplera)

LEARNING_RATE = 0.001
NUM_EPOCHS = 50
HIDDEN_DIM = 64
DROPOUT = 0.3
BATCH_SIZE = 4

from sklearn.model_selection import train_test_split
    
print("\n🔀 Tworzę split train/validation (80/20)...")
train_indices, val_indices = train_test_split(
        list(range(len(train_data['slides']))),
        test_size=0.2,
        random_state=42,
        stratify=train_data['labels']
    )
    
train_split_data = {
    'slides': [train_data['slides'][i] for i in train_indices],
    'labels': train_data['labels'][train_indices],
    'filenames': [train_data['filenames'][i] for i in train_indices]
    }
    
val_data = {
    'slides': [train_data['slides'][i] for i in val_indices],
    'labels': train_data['labels'][val_indices],
    'filenames': [train_data['filenames'][i] for i in val_indices]
    }
    
print(f"  Train: {len(train_split_data['slides'])} slajdów")
print(f"  Val:   {len(val_data['slides'])} slajdów")
print(f"  Test:  {len(test_data['slides'])} slajdów")
    
train_dataset = SlideDataset(train_split_data)
val_dataset = SlideDataset(val_data)
test_dataset = SlideDataset(test_data)

# --- Początek implementacji WeightedRandomSampler --- # <--- DODANE

print("\n⚖️ Tworzę WeightedRandomSampler dla zbioru treningowego...")

# 1. Pobierz etykiety ze zbioru treningowego
train_labels = train_dataset.labels 

# 2. Oblicz liczebność każdej klasy
class_counts = np.bincount(train_labels)
num_samples = len(train_labels)
num_classes = len(class_counts)

# 3. Oblicz wagi dla każdej KLASY (formuła "balanced")
class_weights = num_samples / (num_classes * class_counts)
print(f"  Obliczone wagi klas: {class_weights}")

# 4. Utwórz listę wag dla każdej PRÓBKI
sample_weights = [class_weights[label] for label in train_labels]

# 5. Stwórz sampler
sampler = WeightedRandomSampler(
    weights=torch.tensor(sample_weights, dtype=torch.float),
    num_samples=len(sample_weights),
    replacement=True  # replacement=True pozwala na nadpróbkowanie (oversampling)
)

# --- Koniec implementacji WeightedRandomSampler --- # <--- DODANE

train_loader = DataLoader(
    train_dataset, 
    batch_size=BATCH_SIZE, 
    # shuffle=True,  <--- ZMIENIONE (nie można używać shuffle z samplerem)
    shuffle=False,   # <--- ZMIENIONE (sampler sam zajmuje się losowością)
    sampler=sampler, # <--- DODANE (przekazujemy nasz sampler)
    collate_fn=collate_fn
    )

val_loader = DataLoader(
    val_dataset, 
    batch_size=BATCH_SIZE, 
    shuffle=False, 
    collate_fn=collate_fn
    )

test_loader = DataLoader(
    test_dataset, 
    batch_size=BATCH_SIZE, 
    shuffle=False, 
    collate_fn=collate_fn
    )

print("✅ Dataloadery gotowe (train_loader używa samplera).")

🔀 Tworzę split train/validation (80/20)...
  Train: 261 slajdów
  Val:   66 slajdów
  Test:  82 slajdów

⚖️ Tworzę WeightedRandomSampler dla zbioru treningowego...
  Obliczone wagi klas: [     1.1013       2.175     0.61268]
✅ Dataloadery gotowe (train_loader używa samplera).

In [44]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\n🖥️ Używam urządzenia: {device}")
    
model = AttentionMIL(
        input_dim=3, 
        hidden_dim=HIDDEN_DIM, 
        num_classes=len(CLASS_NAMES), 
        dropout=DROPOUT).to(device)
    
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    
# Training loop
best_val_acc = 0
patience = 50
patience_counter = 0
    
print("\n🚀 Rozpoczynam trening...")
for epoch in range(NUM_EPOCHS):
    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
    val_loss, val_acc = validate(model, val_loader, criterion, device)
        
    # Early stopping based on validation accuracy
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), 'best_attention_mil_model.pth')
        patience_counter = 0
        print(f"✓ Zapisano najlepszy model (val acc: {best_val_acc:.2f}%)")
    else:
        patience_counter += 1
        
    if (epoch + 1) % 10 == 0:
        print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}")
        print(f"  Train - Loss: {train_loss:.4f}, Acc: {train_acc:.2f}%")
        print(f"  Val   - Loss: {val_loss:.4f}, Acc: {val_acc:.2f}%")
        
    # Early stopping
    if patience_counter >= patience:
        print(f"\n⏹️ Early stopping - brak poprawy przez {patience} epok. Koniec treningu na epoce {epoch+1}.")
        break


# Load best model i szczegółowa ewaluacja
print("\n" + "="*60)
print("📊 FINALNA EWALUACJA")
print("="*60)
model.load_state_dict(torch.load('best_attention_mil_model.pth'))
evaluate_detailed(model, test_loader, device, CLASS_NAMES)
    
# Przykład wizualizacji attention dla pierwszego slajdu testowego
if len(test_data['slides']) > 0:
    print("\n" + "="*60)
    print("👁️ PRZYKŁADOWA WIZUALIZACJA ATTENTION")
    print("="*60)
    visualize_attention(
        model, 
        test_data['slides'][0], 
        test_data['filenames'][0],
        device, 
        CLASS_NAMES
    )

🖥️ Używam urządzenia: cpu

🚀 Rozpoczynam trening...
✓ Zapisano najlepszy model (val acc: 59.09%)
✓ Zapisano najlepszy model (val acc: 66.67%)
✓ Zapisano najlepszy model (val acc: 72.73%)
✓ Zapisano najlepszy model (val acc: 74.24%)
✓ Zapisano najlepszy model (val acc: 78.79%)

Epoch 10/50
  Train - Loss: 0.6379, Acc: 76.63%
  Val   - Loss: 0.5691, Acc: 72.73%
✓ Zapisano najlepszy model (val acc: 81.82%)
✓ Zapisano najlepszy model (val acc: 83.33%)

Epoch 20/50
  Train - Loss: 0.5700, Acc: 75.86%
  Val   - Loss: 0.4649, Acc: 77.27%
✓ Zapisano najlepszy model (val acc: 84.85%)
✓ Zapisano najlepszy model (val acc: 87.88%)

Epoch 30/50
  Train - Loss: 0.5468, Acc: 78.54%
  Val   - Loss: 0.3965, Acc: 81.82%

Epoch 40/50
  Train - Loss: 0.5859, Acc: 77.39%
  Val   - Loss: 0.3759, Acc: 81.82%

Epoch 50/50
  Train - Loss: 0.6596, Acc: 71.65%
  Val   - Loss: 0.3463, Acc: 81.82%

============================================================
📊 FINALNA EWALUACJA
============================================================

📊 Confusion Matrix:
[[16  7  1]
 [ 3  9  1]
 [ 0  3 42]]

📈 Classification Report:
              precision    recall  f1-score   support

        HSIL       0.84      0.67      0.74        24
        LSIL       0.47      0.69      0.56        13
        NSIL       0.95      0.93      0.94        45

    accuracy                           0.82        82
   macro avg       0.76      0.76      0.75        82
weighted avg       0.85      0.82      0.82        82


❌ Błędnie sklasyfikowane (15 próbek):
  23a.bmp: True=HSIL, Pred=LSIL
  35c.bmp: True=HSIL, Pred=LSIL
  36a.bmp: True=HSIL, Pred=LSIL
  40a.bmp: True=HSIL, Pred=LSIL
  46a.bmp: True=HSIL, Pred=LSIL
  52c.bmp: True=HSIL, Pred=NSIL
  58a.bmp: True=HSIL, Pred=LSIL
  60b.bmp: True=HSIL, Pred=LSIL
  10b.bmp: True=LSIL, Pred=NSIL
  22a.bmp: True=LSIL, Pred=HSIL

============================================================
👁️ PRZYKŁADOWA WIZUALIZACJA ATTENTION
============================================================

🔍 Analiza slajdu: 10b.bmp
  Predicted class: HSIL
  Top 5 important cells (attention weights):
    Cell 1: weight=0.0904, probs=[   0.020938     0.94096    0.038107]
    Cell 4: weight=0.0901, probs=[   0.014511     0.93675    0.048744]
    Cell 2: weight=0.0883, probs=[   0.018519      0.8899    0.091578]
    Cell 7: weight=0.0862, probs=[   0.036699     0.83709     0.12621]
    Cell 12: weight=0.0817, probs=[     0.8999    0.098545   0.0015561]

In [27]:
test_data['slides'][2]

[array([    0.99041,   0.0084711,   0.0011145]),
 array([    0.78616,     0.21268,   0.0011586]),
 array([    0.87998,     0.11351,   0.0065141]),
 array([    0.92606,     0.07203,   0.0019153]),
 array([     0.9952,   0.0036367,   0.0011634]),
 array([  0.0049988,      0.9863,    0.008705])]

In [28]:
slide = [np.array([ 2.7886e-05,     0.99584,   0.0041329]), np.array([  0.0024515,     0.98735,    0.010195]), np.array([  0.0021589,      0.9906,   0.0072459]), np.array([  8.206e-06,      0.9979,   0.0020924]), np.array([  0.0020331,       0.992,   0.0059672]), np.array([    0.89986,    0.060451,    0.039688]), np.array([   0.015794,     0.98037,   0.0038368]), np.array([ 3.6391e-05,     0.99538,   0.0045857])]
visualize_attention(model, slide, 'test', device, CLASS_NAMES)

🔍 Analiza slajdu: test
  Predicted class: LSIL
  Top 5 important cells (attention weights):
    Cell 3: weight=0.1294, probs=[  8.206e-06      0.9979   0.0020924]
    Cell 0: weight=0.1292, probs=[ 2.7886e-05     0.99584   0.0041329]
    Cell 7: weight=0.1292, probs=[ 3.6391e-05     0.99538   0.0045857]
    Cell 4: weight=0.1288, probs=[  0.0020331       0.992   0.0059672]
    Cell 2: weight=0.1287, probs=[  0.0021589      0.9906   0.0072459]

(1,
 array([     0.1292,     0.12838,     0.12871,     0.12941,     0.12885,    0.098377,     0.12793,     0.12915], dtype=float32))

In [29]:
slide = [np.array([   0.017954,     0.97584,   0.0062091]), np.array([    0.11891,     0.55086,     0.33023]), np.array([    0.99023,   0.0073096,   0.0024576]), np.array([    0.78636,     0.21241,   0.0012248]), np.array([    0.18094,     0.33201,     0.48705]), np.array([    0.99505,   0.0028757,   0.0020769]), np.array([    0.22094,     0.29442,     0.48464]), np.array([    0.94493,     0.05062,   0.0044457]), np.array([    0.99431,   0.0042377,   0.0014509]), np.array([     0.9954,   0.0017875,    0.002812])]
visualize_attention(model, slide, 'test', device, CLASS_NAMES)

🔍 Analiza slajdu: test
  Predicted class: HSIL
  Top 5 important cells (attention weights):
    Cell 0: weight=0.1414, probs=[   0.017954     0.97584   0.0062091]
    Cell 8: weight=0.1177, probs=[    0.99431   0.0042377   0.0014509]
    Cell 5: weight=0.1177, probs=[    0.99505   0.0028757   0.0020769]
    Cell 9: weight=0.1176, probs=[     0.9954   0.0017875    0.002812]
    Cell 2: weight=0.1174, probs=[    0.99023   0.0073096   0.0024576]

(0,
 array([    0.14145,    0.073046,     0.11744,     0.11129,    0.045644,     0.11765,    0.042719,     0.11548,      0.1177,     0.11758], dtype=float32))

In [31]:
slide = [np.array([   0.071536,    0.072288,     0.85618]), np.array([  0.0019841,    0.002361,     0.99565]), np.array([  0.0060997,    0.010887,     0.98301]), np.array([  0.0021393,   0.0049249,     0.99294]), np.array([   0.015889,    0.035407,      0.9487]), np.array([  0.0022652,   0.0023194,     0.99542]), np.array([   0.015033,    0.013413,     0.97155]), np.array([    0.03418,     0.14673,     0.81909])]
visualize_attention(model, slide, 'test', device, CLASS_NAMES)

🔍 Analiza slajdu: test
  Predicted class: NSIL
  Top 5 important cells (attention weights):
    Cell 1: weight=0.1297, probs=[  0.0019841    0.002361     0.99565]
    Cell 5: weight=0.1297, probs=[  0.0022652   0.0023194     0.99542]
    Cell 3: weight=0.1295, probs=[  0.0021393   0.0049249     0.99294]
    Cell 2: weight=0.1286, probs=[  0.0060997    0.010887     0.98301]
    Cell 6: weight=0.1273, probs=[   0.015033    0.013413     0.97155]

(2,
 array([    0.11589,      0.1297,     0.12856,     0.12949,     0.12546,     0.12968,     0.12732,     0.11391], dtype=float32))

In [33]:
slide = [np.array([  0.0095552,     0.78267,     0.20777]), np.array([    0.35931,     0.63454,   0.0061475]), np.array([    0.99708,   0.0013094,     0.00161]), np.array([   0.039165,    0.059247,     0.90159]), np.array([  0.0047941,   0.0086451,     0.98656]), np.array([  0.0025545,   0.0095348,     0.98791]), np.array([ 1.5846e-05,     0.99705,   0.0029352]), np.array([  0.0036693,   0.0096488,     0.98668]), np.array([    0.99525,   0.0036332,   0.0011165]), np.array([    0.56378,     0.41279,    0.023428]), np.array([  0.0023887,   0.0023697,     0.99524]), np.array([      0.996,   0.0022685,    0.001731]), np.array([    0.99725,   0.0015455,   0.0012033]), np.array([    0.79784,     0.10787,    0.094291]), np.array([   0.019801,   0.0076358,     0.97256]), np.array([   0.013904,    0.012752,     0.97334])]
visualize_attention(model, slide, 'test', device, CLASS_NAMES)

🔍 Analiza slajdu: test
  Predicted class: HSIL
  Top 5 important cells (attention weights):
    Cell 6: weight=0.0928, probs=[ 1.5846e-05     0.99705   0.0029352]
    Cell 0: weight=0.0784, probs=[  0.0095552     0.78267     0.20777]
    Cell 12: weight=0.0754, probs=[    0.99725   0.0015455   0.0012033]
    Cell 2: weight=0.0754, probs=[    0.99708   0.0013094     0.00161]
    Cell 11: weight=0.0753, probs=[      0.996   0.0022685    0.001731]

(0,
 array([   0.078354,    0.072052,    0.075391,    0.044412,    0.047374,    0.047446,    0.092848,    0.047394,    0.075331,    0.064281,    0.047658,    0.075344,     0.07541,    0.063066,    0.046775,    0.046863], dtype=float32))

## KFOLD

In [46]:
def get_detailed_metrics(model, dataloader, device, class_names):
    """
    Zwraca szczegółowe metryki (jako słownik) dla danego modelu i dataloadera.
    """
    model.eval()
    all_preds = []
    all_labels = []
    
    with torch.no_grad():
        for slides, labels, _ in dataloader:
            slides, labels = slides.to(device), labels.to(device)
            outputs, _ = model(slides)
            _, predicted = torch.max(outputs, 1)
            
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    
    # Tłumienie ostrzeżeń sklearn (na wypadek zerowej precyzji/recall)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        report = classification_report(
            all_labels, 
            all_preds, 
            target_names=class_names, 
            output_dict=True  # Zwraca słownik
        )
    
    return report

In [48]:
import copy


print("\n🔄 Rozpoczynam Walidację Krzyżową (Stratified K-Fold)...")

# 4. Przygotowanie danych do K-Fold
all_slides = train_data['slides']
all_labels = np.array(train_data['labels']) # Ważne: Konwersja na np.array
all_filenames = train_data['filenames']
X_indices = np.arange(len(all_slides))
y_labels = all_labels

skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

# 5. Listy do przechowywania wyników
fold_val_accuracies = []
fold_hsil_recalls = [] # Do śledzenia recall HSIL

# --- Główna Pętla K-Fold ---
for fold, (train_indices, val_indices) in enumerate(skf.split(X_indices, y_labels)):
    
    print(f"\n--- FOLD {fold + 1}/{N_SPLITS} ---")
    
    # 6. Stwórz dane dla tego foldu
    fold_train_data = {
        'slides': [all_slides[i] for i in train_indices],
        'labels': all_labels[train_indices],
        'filenames': [all_filenames[i] for i in train_indices]
    }
    fold_val_data = {
        'slides': [all_slides[i] for i in val_indices],
        'labels': all_labels[val_indices],
        'filenames': [all_filenames[i] for i in val_indices]
    }

    # 7. Stwórz Datasety
    train_dataset = SlideDataset(fold_train_data)
    val_dataset = SlideDataset(fold_val_data)
    
    print(f"  Train: {len(train_dataset)} slajdów, Val: {len(val_dataset)} slajdów")

    # 8. Stwórz WeightedRandomSampler DLA TEGO FOLDU
    train_labels_fold = train_dataset.labels
    class_counts = np.bincount(train_labels_fold)
    num_samples = len(train_labels_fold)
    
    # Oblicz wagi, unikając dzielenia przez zero (jeśli jakaś klasa ma 0 próbek)
    class_weights = num_samples / (len(class_counts) * np.where(class_counts == 0, 1, class_counts))
    # Ustaw wagę na 0 dla klas, które nie istnieją
    class_weights[class_counts == 0] = 0 
    
    sample_weights = [class_weights[label] for label in train_labels_fold]
    
    sampler = WeightedRandomSampler(
        weights=torch.tensor(sample_weights, dtype=torch.float),
        num_samples=len(sample_weights),
        replacement=True
    )

    # 9. Stwórz DataLoadery DLA TEGO FOLDU
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        sampler=sampler,
        shuffle=False, # Sampler robi shuffle
        collate_fn=collate_fn
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn
    )

    # 10. Reinicjalizuj model i optymalizator
    print("  Inicjalizuję nowy model...")
    model = AttentionMIL(input_dim=3, hidden_dim=HIDDEN_DIM, num_classes=len(CLASS_NAMES), dropout=DROPOUT).to(device)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    criterion = nn.CrossEntropyLoss() # Standardowa strata (bo mamy sampler)

    best_val_acc = 0.0
    best_model_state = None # Do przechowania wag najlepszego modelu

    # 11. Pętla treningowa dla epok
    for epoch in range(NUM_EPOCHS):
        train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = validate(model, val_loader, criterion, device)
        
        if (epoch + 1) % 10 == 0: # Drukuj co 10 epok
            print(f'  Epoch {epoch+1:2d}/{NUM_EPOCHS} | Train Loss: {train_loss:.4f} Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f} Acc: {val_acc:.2f}%')
        
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_model_state = copy.deepcopy(model.state_dict()) # Zapisz wagi w pamięci

    # --- Koniec Pętli Epok dla Foldu ---
    print(f"  --- Najlepsza dokładność walidacyjna dla foldu {fold+1}: {best_val_acc:.2f}% ---")

    # 12. Ewaluacja najlepszego modelu z tego foldu
    if best_model_state:
        model.load_state_dict(best_model_state) # Wczytaj najlepsze wagi
        val_report = get_detailed_metrics(model, val_loader, device, CLASS_NAMES)
        
        # Wyciągnij recall dla klasy 'HSIL'
        hsil_recall = val_report['HSIL']['recall']
        
        print(f"  📈 Recall HSIL dla najlepszego modelu: {hsil_recall*100:.2f}%")
        fold_hsil_recalls.append(hsil_recall)
    else:
        print("  --- Nie udało się zapisać najlepszego modelu (być może Acc=0.0) ---")
        fold_hsil_recalls.append(0.0)

    fold_val_accuracies.append(best_val_acc)

# --- Koniec Pętli K-Fold ---

# 13. Oblicz i wyświetl średnie wyniki
mean_acc = np.mean(fold_val_accuracies)
std_acc = np.std(fold_val_accuracies)
mean_hsil_recall = np.mean(fold_hsil_recalls)
std_hsil_recall = np.std(fold_hsil_recalls)

print(f"\n\n--- Podsumowanie Walidacji Krzyżowej ({N_SPLITS}-krotnej) ---")
print(f"Wyniki dokładności (Accuracy) dla każdego foldu: {[f'{acc:.2f}%' for acc in fold_val_accuracies]}")
print(f"📈 Średnia dokładność walidacyjna: {mean_acc:.2f}% ± {std_acc:.2f}%")
print("\n")
print(f"Wyniki Recall (HSIL) dla każdego foldu: {[f'{rec*100:.2f}%' for rec in fold_hsil_recalls]}")
print(f"🎯 Średni Recall dla HSIL: {mean_hsil_recall*100:.2f}% ± {std_hsil_recall*100:.2f}%")
print("--------------------------------------------------")

🔄 Rozpoczynam Walidację Krzyżową (Stratified K-Fold)...

--- FOLD 1/5 ---
  Train: 261 slajdów, Val: 66 slajdów
  Inicjalizuję nowy model...
  Epoch 10/50 | Train Loss: 0.6712 Acc: 70.88% | Val Loss: 0.6026 Acc: 75.76%
  Epoch 20/50 | Train Loss: 0.5826 Acc: 73.95% | Val Loss: 0.6329 Acc: 75.76%
  Epoch 30/50 | Train Loss: 0.4780 Acc: 76.63% | Val Loss: 0.6225 Acc: 77.27%
  Epoch 40/50 | Train Loss: 0.4952 Acc: 74.33% | Val Loss: 0.6641 Acc: 74.24%
  Epoch 50/50 | Train Loss: 0.5097 Acc: 78.16% | Val Loss: 0.6776 Acc: 75.76%
  --- Najlepsza dokładność walidacyjna dla foldu 1: 78.79% ---
  📈 Recall HSIL dla najlepszego modelu: 70.00%

--- FOLD 2/5 ---
  Train: 261 slajdów, Val: 66 slajdów
  Inicjalizuję nowy model...
  Epoch 10/50 | Train Loss: 0.5128 Acc: 78.93% | Val Loss: 0.4652 Acc: 77.27%
  Epoch 20/50 | Train Loss: 0.5685 Acc: 76.25% | Val Loss: 0.4576 Acc: 75.76%
  Epoch 30/50 | Train Loss: 0.5423 Acc: 75.86% | Val Loss: 0.4443 Acc: 78.79%
  Epoch 40/50 | Train Loss: 0.5879 Acc: 75.86% | Val Loss: 0.4641 Acc: 77.27%
  Epoch 50/50 | Train Loss: 0.5497 Acc: 73.95% | Val Loss: 0.4782 Acc: 75.76%
  --- Najlepsza dokładność walidacyjna dla foldu 2: 80.30% ---
  📈 Recall HSIL dla najlepszego modelu: 65.00%

--- FOLD 3/5 ---
  Train: 262 slajdów, Val: 65 slajdów
  Inicjalizuję nowy model...
  Epoch 10/50 | Train Loss: 0.6402 Acc: 73.28% | Val Loss: 0.4178 Acc: 75.38%
  Epoch 20/50 | Train Loss: 0.5106 Acc: 78.63% | Val Loss: 0.4354 Acc: 75.38%
  Epoch 30/50 | Train Loss: 0.5903 Acc: 74.43% | Val Loss: 0.4217 Acc: 75.38%
  Epoch 40/50 | Train Loss: 0.5591 Acc: 77.10% | Val Loss: 0.3746 Acc: 76.92%
  Epoch 50/50 | Train Loss: 0.5114 Acc: 75.57% | Val Loss: 0.3782 Acc: 78.46%
  --- Najlepsza dokładność walidacyjna dla foldu 3: 80.00% ---
  📈 Recall HSIL dla najlepszego modelu: 50.00%

--- FOLD 4/5 ---
  Train: 262 slajdów, Val: 65 slajdów
  Inicjalizuję nowy model...
  Epoch 10/50 | Train Loss: 0.6347 Acc: 70.99% | Val Loss: 0.4077 Acc: 89.23%
  Epoch 20/50 | Train Loss: 0.6449 Acc: 70.23% | Val Loss: 0.3910 Acc: 84.62%
  Epoch 30/50 | Train Loss: 0.6182 Acc: 71.37% | Val Loss: 0.3718 Acc: 84.62%
  Epoch 40/50 | Train Loss: 0.6144 Acc: 72.90% | Val Loss: 0.3643 Acc: 84.62%
  Epoch 50/50 | Train Loss: 0.5907 Acc: 72.14% | Val Loss: 0.3719 Acc: 86.15%
  --- Najlepsza dokładność walidacyjna dla foldu 4: 89.23% ---
  📈 Recall HSIL dla najlepszego modelu: 85.00%

--- FOLD 5/5 ---
  Train: 262 slajdów, Val: 65 slajdów
  Inicjalizuję nowy model...
  Epoch 10/50 | Train Loss: 0.6210 Acc: 74.05% | Val Loss: 0.4711 Acc: 80.00%
  Epoch 20/50 | Train Loss: 0.5339 Acc: 78.63% | Val Loss: 0.4359 Acc: 78.46%
  Epoch 30/50 | Train Loss: 0.6158 Acc: 72.14% | Val Loss: 0.4567 Acc: 78.46%
  Epoch 40/50 | Train Loss: 0.5993 Acc: 72.14% | Val Loss: 0.4095 Acc: 78.46%
  Epoch 50/50 | Train Loss: 0.4784 Acc: 78.63% | Val Loss: 0.4003 Acc: 81.54%
  --- Najlepsza dokładność walidacyjna dla foldu 5: 81.54% ---
  📈 Recall HSIL dla najlepszego modelu: 63.16%


--- Podsumowanie Walidacji Krzyżowej (5-krotnej) ---
Wyniki dokładności (Accuracy) dla każdego foldu: ['78.79%', '80.30%', '80.00%', '89.23%', '81.54%']
📈 Średnia dokładność walidacyjna: 81.97% ± 3.73%


Wyniki Recall (HSIL) dla każdego foldu: ['70.00%', '65.00%', '50.00%', '85.00%', '63.16%']
🎯 Średni Recall dla HSIL: 66.63% ± 11.31%
--------------------------------------------------